### ISSUE TITLE
The hotel or room number entered do not match any existing location + Sign file doesn't exist

### ISSUE THREAD

**Issue by crc33** [gvlfm78/BukkitHotels#10]
Please help
1. command: /ht friend add
2. sign: I created sign and it doesn't work
Version: 1.7.X

**Comment by crc33** [comment]
And I created 80 rooms I don't wan't to create them again.

**Comment by crc33** [comment]
I finally solved the problem. The problem was in hotel name it's name was GrandHotel, but this not existed. I wrote Grandhotel instead of GrandHotel and now it's working well.
Thanks for great plugin

**Comment by gvlfm78** [comment]
The hotel name capitalisation interfering with the correct functioning of the plugin has been fixed in Hotels 0.4.2.
