### ISSUE TITLE
Reception sign not working correctly.

### ISSUE THREAD

**Issue by SharkZs** [gvlfm78/BukkitHotels#11]
When I create a reception sign all is well. But once finished, the display is without syntax.
![2015-08-05_21 30 45](https://cloud.githubusercontent.com/assets/13666321/9095981/c09adb14-3bba-11e5-958c-f7e7c763d5f4.png)

I create the sign like this :
[Hotels]
lod

Thanks on advance.

**Comment by gvlfm78** [comment]
I will see about this bug as soon as I get back, in a few days. It should
be easy to fix anyway.
Il 05/ago/2015 21:42, "SharkZs" <notifications@github.com> ha scritto:

**Comment by SharkZs** [comment]
Thank you for the reply and thank you for the support :)

**Comment by gvlfm78** [comment]
I have fixed this bug in Hotels 0.4.2
