### ISSUE TITLE
Using buttons and having items in chests

### ISSUE THREAD

**Issue by goodsteak99** [gvlfm78/BukkitHotels#12]
@gvlfm78 Well first of all I have buttons in my hotels lobby and players cannot use them and secondly when players put items in a chest in a rented room they dont get their stuff back after the rent is up.
Also people seem to get stuck in their room after the rent expires

**Comment by gvlfm78** [comment]
That is how the hotels work. Players are not allowed to use things outside of their rented rooms. You can though change manually the use flag using world guard, doing /rg f hotel-hotelname use true . To get their items back when their rent expires they have to rent the room again, what other way is there? And players should be able to teleport out of their rooms when stuck inside. There is though a teleport feature coming in the next version of hotels for players to teleport to the hotel main area and into their rented rooms.
