### ISSUE TITLE
Welcome/Goodbye Messages Broken

### ISSUE THREAD

**Issue by Siniscarrrrrrrr** [gvlfm78/BukkitHotels#13]
Hey there @gvlfm78 ! I don't think this has come up yet, and if it has I didn't see the fix. For some reason, on my hotel, the "Welcome to..." and "Come again soon to..." messages are both broken in different ways.

The welcome message is stuck in red text, and even though it's changed in the config (And wasn't supposed to be red text in the original config either), it still shows up in game as pale red text.

As for the leaving message, its color code is broken and set to &g, which isn't even a color code to begin with. Again, this isn't what it was listed as in the original config, but still what it showed up as in the game. Again once more, after changing it in the config to a custom message color and such, it still is broken and will not change.

I've uninstalled and reinstalled the plugin, restarted the server, restarted the plugin, even checked the plugin.yml in the jar as well. Nothing seems to be able to be done about this.

**Comment by gvlfm78** [comment]
What version of WorldGuard are you sing? The colour codes changed in version 6

**Comment by Siniscarrrrrrrr** [comment]
I'm using version 6.1

**Comment by gvlfm78** [comment]
What colour does using &r give you?

2015-09-16 3:31 GMT+02:00 Scarrlet <notifications@github.com>:

**Comment by Siniscarrrrrrrr** [comment]
&r is the reset code to remove any colors or bold/italics for me.

**Comment by gvlfm78** [comment]
Therefore check if these colours work for you http://ess.khhq.net/mc/

2015-09-16 8:15 GMT+02:00 Scarrlet <notifications@github.com>:

**Comment by Siniscarrrrrrrr** [comment]
Yes, those are the ones that do work.

**Comment by gvlfm78** [comment]
Good to know that it works now.
