### ISSUE TITLE
Non-Rectangular Rooms

### ISSUE THREAD

**Issue by Siniscarrrrrrrr** [gvlfm78/BukkitHotels#14]
Hello again @gvlfm78 ! I apologize for not simply putting this in the same message as my other ticket, but it's really its own problem entirely. Though, I suppose it's more of a general question.

Due to the shape of my hotel, the rooms are not just simply rectangles. Many of them have a curve or offset piece to them that, if marked as a rectangle, would overlap some of the floor's hallway.

Is there a way to properly make rooms that are non-rectangular, or is that out of the question of this plugin?

**Comment by gvlfm78** [comment]
Not how the plugin is currently coded, but I will loook into allowing this for the next version(s).

**Comment by gvlfm78** [comment]
I was looking into this, but I would need to know what kind of non-cuboid regions you had in mind.

**Comment by Siniscarrrrrrrr** [comment]
Think of the shape of the L piece in Tetris, essentially. The room is shaped like that, with the hallway outside of it.

**Comment by gvlfm78** [comment]
And what way would you select it using woldedit? (Through the //Sel commands?)

**Comment by Siniscarrrrrrrr** [comment]
I normally just use //pos1 and //po2

**Comment by gvlfm78** [comment]
But would you end up with a non cuboid selection? I mean, if you then defined a region using the /rg command with the L selection, would the region become non-cuboid? You can check by right-clicking the ground with a piece of leather)

**Comment by Siniscarrrrrrrr** [comment]
I hadn't thought of that, actually... To be totally honest, I'm not proficient in WorldEdit, so I didn't actually know you could make non-cuboid region selections.

**Comment by gvlfm78** [comment]
Well I have added support for hotel & room polygonal regions and it will be coming in the next version of the plugin. For how to select polygonically, I found this tutorial on youtube: (https://www.youtube.com/watch?v=1Ew5lQUi33w) (you don't have to expand vert, you can //expand 5 up and //expand 56 down etc.)
