### ISSUE TITLE
room delete does not remove sign

### ISSUE THREAD

**Issue by Dizfunkshunal** [gvlfm78/BukkitHotels#16]
ok I created a hotel and rooms, after wards I realized the building was not facing the street. So I used world edit and rotated the building. I deleted the hotel and rooms. Then made a new hotel with a new name and rooms. But now When i try to place the signs it keeps telling me "Sign for this hotel room already exists!

hotels 0.5.3

**Comment by gvlfm78** [comment]
I have found what the problem was, the plugin wasn't deleting the sign files for deleted rooms. I have fixed this in Hotels 0.6 which should be coming out soon.

**Comment by Dizfunkshunal** [comment]
Thanks
