### ISSUE TITLE
Unable to remove player from their room

### ISSUE THREAD

**Issue by Dizfunkshunal** [gvlfm78/BukkitHotels#17]
While testing to make sure everything works. I had a player rent a room, he actually rented 3. I tried using the /ht reomve playername hotelname roomnumber     to remove him from the rooms and it says

The Specified room has not been rented,

Spigot 1.9.2
Hotels 0.5.3

**Comment by gvlfm78** [comment]
How did he "actually rent three"

**Comment by Dizfunkshunal** [comment]
yes he rented 3, i dont know why he just did.

**Comment by gvlfm78** [comment]
Ok, I will wait for you to do that, and would also like to know what plugin it was. And, did the user rent 3 separate rooms? Does it appear on the signs and when doing /ht check playerName?

I would need this information as I will be releasing Hotels 0.6 very soon and wouldn't want any bugs lurking around in a new release :)

**Comment by Dizfunkshunal** [comment]
ok after re- install and re testing with out that 1.8pvp plugin. everything is working as intended. Im sorry I had no idea that plugin would mess up so many other plugins that it should have nothing to do with at all.

**Comment by gvlfm78** [comment]
Ok thanks for checking for me. Hotels 0.6 should be coming out either tomorrow or the day after.

**Comment by Dizfunkshunal** [comment]
np any time.
