### ISSUE TITLE
dal plugin che non funziona ai consigli

### ISSUE THREAD

**Issue by MCG-server** [gvlfm78/BukkitHotels#18]
hello I have tried both with spigot and also paperspigot but your plugin does it bugga ( rarely goes ) , (my server is 1.8 ) I tried 3 your plugin versions : 0.6 , 0.5.3 and 0.5.2 the last version ( o.5.2 ) l I put for the first time I went restartato the server and not going more ...... what should I do ??

**Comment by MCG-server** [comment]
you are italian???

**Comment by gvlfm78** [comment]
I am Italian. What is the error you are getting?

**Comment by MCG-server** [comment]
anche io sono italiano dicevo
in poche parole metto il plugin lo legge ma quando faccio help hotels non mi da niente 
però il pluginner di TTT per minecrfat mi ha passato una specie di spigot lo caricato la è funziona ma non so se funziona per sempre o si ribugga

**Comment by MCG-server** [comment]
ora provo a rimetterlo dove si buggava e vedo se funziona se non funziona sra un grosso problema

**Comment by gvlfm78** [comment]
Sei fai /hotels succede niente?

**Comment by MCG-server** [comment]
niente

**Comment by MCG-server** [comment]
ok funziona ma devi cercare di risolvere questo problema
non so come posso aiutarti ma farò l impossibile
hai skype o qualcosa del genere?

**Comment by gvlfm78** [comment]
Nella console appare niente? Quando parte il server, appare scritto Hotels da qualche parte?

**Comment by MCG-server** [comment]
leggi il commento sopra
nella mia console diciamo che non ci capisco grand che

**Comment by MCG-server** [comment]
se vuoi ti posso inviare il log

**Comment by gvlfm78** [comment]
Copia e incolla su http://pastebin.com/ che ci capisco io

**Comment by MCG-server** [comment]
ma io ho riavviato la console e fatto clear log ma copio incollo lultimo log che credo che li c'è anche l errore

**Comment by gvlfm78** [comment]
Sì e manda il link qui

**Comment by MCG-server** [comment]
http://pastebin.com/0EdPWchM

**Comment by MCG-server** [comment]
spero che c'è l errore

**Comment by gvlfm78** [comment]
Vi sono molti plugin che non funzionano, quali:

- Youtuber (dato che la versione di Java del server o del plugin è troppo vecchia)
- Holographic Displays Patcher (Possibilmente data la versione troppo aggiornata di HoloGraphicDisplays, ti server questa http://dev.bukkit.org/bukkit-plugins/holographic-displays/files/67-holographic-displays-v2-1-10/)

Prova prima ad aggiustare queste cose - potresti anche provare ad entrare normalmente e senza VanishNoPacket

**Comment by MCG-server** [comment]
holographic va anche si la da errore l host che mi gestisce il server ha java7 no java8

**Comment by gvlfm78** [comment]
Ma può interferire con altri plugin, come Hotels.

**Comment by MCG-server** [comment]
ok provo a vedre se metto quella versione funziona , esiste un plugin che va sul ora di minercfat (non vogliu utilizare i sensori di luce ) perche mi servirebbe di fare una cosa che dalle 7:30pm (ora minecrfat) fino alle 8:00am rimane chiusa tipo un percorso

**Comment by MCG-server** [comment]
ti ripasso il og per vedere se ho sitemato

**Comment by MCG-server** [comment]
http://pastebin.com/4m84upBD    vedi se ho risolto il problema?

**Comment by MCG-server** [comment]
di holographic per favore
una domanda c'è questo plugin che mi piacerebbe metterlo nel mio server : http://dev.bukkit.org/bukkit-plugins/elevatorsion/  però non funziona non è che potresti vedere perche non funziona?? se si lo potrtesti modificare che invece di andare a scatti (come fa vedere nl video ) va fluido ???

**Comment by gvlfm78** [comment]
- Non so che versione di Youtuber hai, ma prova con questa http://dev.bukkit.org/media/files/910/428/Youtuber.jar
- Hai intenzione di far entrare sul server sia persone con l'1.7 che l'1.8? Perchè se no dovresti aggiornare Spigot
- Prova con questo plugin per gli ascensori http://dev.bukkit.org/bukkit-plugins/lift/
- Prova con questa versione di ProtocolLib http://ci.shadowvolt.com/job/ProtocolLib/10/artifact/ProtocolLib/target/ProtocolLib.jar

**Comment by MCG-server** [comment]
io ho scelto elevatorsion perche era quello piu reale questi altri devi clicacre sul cartello e scegliere il piano ... ci vuole un sacco a spiegarlo q tutti quelli che entrano provo con le versioni che mi hai dato

**Comment by MCG-server** [comment]
voglio far entrare persone con la 1.8
perche credo con la 1.7 possono fare qualcosa con le hack tipo l opsign

**Comment by MCG-server** [comment]
poi il bello che la versione di elevatorsion è 1.7.9 dovrebbe andare con la 1.8

**Comment by MCG-server** [comment]
mi potresti dare qualcosa per restare in contatto per eventuali bug o consigli ??

**Comment by gvlfm78** [comment]
- Allora prova a rimuovere HoloGraphicDisplaysPatcher ed installa questa versione di Spigot http://getspigot.org/jenkins/job/Spigot/6/artifact/spigot-1.8.8.jar
- Prendi questa versione di protocollib https://www.spigotmc.org/resources/protocollib.1997/download?version=73870

**Comment by MCG-server** [comment]
ma se non mi vanno altri plugin?
tipo quelli della 1.7.9 visto che la 1.8.8 e piu aggiornata??

**Comment by MCG-server** [comment]
io ho sempre usato la 1.8 perche voglio utilizare anche i plugin della 1.7.9 c'è un plugin che si chiama utrain una cosa del genre che introduce la possibilità di fare dei treni ma è solo per 1.7.9 funzionerò anche per 1.8.8??

**Comment by MCG-server** [comment]
vuoi che ti rimando i logs ?? o ci sono ancora dei problemi da risolvere?

**Comment by MCG-server** [comment]
allora io ora devo andare via quindi non uso il pc ma il telefono ma nel tuo plugin c'è la possbilita di dare una stanza a random??ti starai chiedendo in che senso facciamo finta che io metto un villager come "ragazzo " della receptions e voglio che quando i player lo cliccano gli fanno vedere le stanze disponibile (ovviamnete le stanza le devi mettere), cioè  quando loro cliccacno io voglio che si vedono determinate stanza (scelte da me ) per esempio: arriva uno clicca il villager e gli escono solo le stanza normali tipo 101,102,103 ma non 401,402,403 che sono le suite (A PROPOSITO DEVI METTERE CHE LE STANZA si possono mettere non solo a numeri ma anche a lettere tipo a posto di 101 magari suite ) non so se hai capito ...se non hai capito o hai qualche dubbio ti prego di rispondermi cosi mi spiego meglio ...magari con qualche frase in meno

**Comment by MCG-server** [comment]
credo che il plugin che dico io del villager sia https://www.spigotmc.org/resources/customgui-completely-customizable.7386/  o se no (questo però invece del villagere devi cliccare un cartello o un items ) http://dev.bukkit.org/bukkit-plugins/chest-commands/

**Comment by MCG-server** [comment]
o lo potresti implementare nel tuo plugin 
che sarebbe una cosa meglio

**Comment by MCG-server** [comment]
attendo una tua risposta ....grazie per avermi aiutato con i problemi

**Comment by MCG-server** [comment]
si lo so è spam ma se vuoi magari vedere il mio server (che ho fatto tutto da solo )inviami un messaggio cosi ti do l ip

**Comment by gvlfm78** [comment]
Il plugin chestcommands lo dovresti usare in congiunzione con Citizens http://dev.bukkit.org/bukkit-plugins/citizens/files/52-2-0-16-beta-1-for-mc-1-8-8/

**Comment by MCG-server** [comment]
Ma quella cosa delle camere random??

**Comment by MCG-server** [comment]
Beh no asp non server più se uso il villager... Ma c'è il commando per dare la stanza tipo /ht buyroom nome stanza 
Ma c'è la possibilità di mettere il nome della stanza non a numeri ma anche a lettere ?

**Comment by MCG-server** [comment]
A che domanda hai risposto ? A quello del nome della stanza o del commando /buy room nome stanza ?? O a tutte e due ??

**Comment by gvlfm78** [comment]
Ad entrambe. SI potrebbe però aggiungere il comando _/ht rent nomeHotel_ senza specificare la stanza ed il plugin sceglierebbe il primo numero disponibile.

**Comment by MCG-server** [comment]
ok ci sta . ma se metti caso io ho creato camere per i vip che voglio solo che i vip le possono comprare se un playernormale fa il commando /ht rent nomeHotel puo capiatre che affita la camera dei vip .....aa piu che altro io voglio una cosa per collegare ad un gui come ho detto i precendenza cio tipo chestCommand che apri il menu e ti fa vedere quali camere sono disponibile (con le informazioni: prezzo, nome stanza ecc) e quale sono gia affittate se vogliono affitare una camera loro cliccano con il tasto destro sopra e la affittano ....o se no metti che possiamo piazzare piu cartelli ...non so se mi hai capito  cioe cosi è una cosa mi carina (ovviamnete i cartelli rimngono anche se c'è chestcommand)

**Comment by MCG-server** [comment]
IN POCHE PAROLE
..non per forza chestcommand anche customgui .... una gui (menu non so come si chaiam è il menu della chest quando la apri) dove il founder puo decidere che stanza mettere (farle vedere) e quali lasciare che le dovono comprare cliccando sul cartello ...per fare questa cosa con chestcommand o altri plugin simili servirebbe il commando /ht rent nomeHotel nomeStanza ....... mi spieghi perchè non vuoi mettere che le stanze possono essere chiamate anche con le lettere per esempio : suite

**Comment by MCG-server** [comment]
oi allora che ne pensi?

**Comment by gvlfm78** [comment]
Il problema è che ChestCommands non ha una API, quindi dal mio plugin non posso modificare le GUI direttamente. Se si trova un altro plugin simile che però abbia un API sarebbe fattibile. Credo che non aggiungerò il fatto di poter omettere il numero della stanza per il comando rent per ciò che hai detto tu, il fatto che si potrebbe per errore spendere uno sproposito acquistando una stanza più costosa.

Quindi ora tocca trovare un plugin per le GUI con un API.
