### ISSUE TITLE
Deleted Hotel, welcome to room # msg still shows

### ISSUE THREAD

**Issue by cmdrlanc73** [gvlfm78/BukkitHotels#19]
I can't figure out how to remove the rooms with the hotel gone.

**Comment by gvlfm78** [comment]
It should be doing it automatically - what version of hotels, worldguard and bukkit/spigot are you using?

Also you can do_ /rg list_ and you should find the _hotel-hotelName-roomNum_ regions for the hotel you dleeted and you should be able to remove them with _/rg remove regionName_

**Comment by gvlfm78** [comment]
Fixed with Hotels 0.6.2
