### ISSUE TITLE
Error message "hotel does not exist" appears when typing in name of existing hotel

### ISSUE THREAD

**Issue by eirikh1996** [gvlfm78/BukkitHotels#2]
I used this plugin and after creating the hotel i should place some signs for rooms and reception. 
What i expected to happen:
A rent room/reception sign should appear

What really happened:
I got the error message "hotel does not exist" when i know it does.

**Comment by gvlfm78** [comment]
First of all, did you create the sign following the instructions? https://github.com/gvlfm78/BukkitHotels/wiki/How-to-use-it

Second, if it still doesn't work, what did you call your hotel and what exactly did you put on the signs?

**Comment by eirikh1996** [comment]
Yes

I called it SkyView, and yes, i did the following

Room sign:

1st line: [Hotels]
2nd line: SkyView (name of hotel)
3rd line: 1:10k
4th line: 5d 3h 6m

Reception sign:
1st line: [Hotels]
2nd line: SkyView (Name of hotel)

Still, either the signs does not change or i get the error message saying "Hotel does not exist" even when the name of the hotel appears in the list when typing /hotels list

**Comment by eirikh1996** [comment]
Yes, I did follow the instructions

And here is what i wrote:

[Hotels]
Skyview
1:10000
7d

and on the reception sign:

[Hotels]
Skyview

Skyview is what i called my hotel. But still, i get this error message saying: "Hotel does not exist" even when its name appears in the list of hotels.

**Comment by gvlfm78** [comment]
Evn though the plugin is ment to ignore capitalisation, try writing "SkyView" on the signs instead of "Skyview"
