### ISSUE TITLE
Messaggi allo scadere dell'affitto

### ISSUE THREAD

**Issue by MCG-server** [gvlfm78/BukkitHotels#20]
ciao un consiglio (o forse è buggato ) potresti aggiungere che se i player mettono la robba nelle chest qunado scade la camera gli da la roba dalle chest o qualcosa del genre??

**Comment by gvlfm78** [comment]
E dove la metterebbe la roba? Quando scade l'affitto la roba rimane nella camera, e se ri-affitti la camera puoi riprenderti la roba. C'è anche un'opzione nel **config.yml** che, se abilitata, permette a chiunque di entrare nella stanza ed accedere alle casse quando non è affittata.

**Comment by MCG-server** [comment]
nel inventario del player o almeno se digita un commando avrà la sua roba ..  se attivo quel opzione chiunque puo entrare e prendersi la robba (se implementi il commando priva che la camera scada deve inviare un messaggio che se digita quel commando riavrà  la sua roba che ha messo nelle chest ) ...e che quando la camera è scaduta la porta si chiude
cioe tipo quando crei la stanza viene salvato l interno e poi quando uno smete di pagarla ed è scaduta rimette come ha salvato la stanza quando è stata creata . se non capisci perchè ho scritto male dimmi cosa non hai capito (o da dove) e lo riscrivo meglio.

**Comment by MCG-server** [comment]
lascia perde il fatto della porta
è abbastanza inutile ma il fatto di salvare la stanza no

**Comment by gvlfm78** [comment]
Il fatto di salvare la stanza è già pianificato per la version 0.7.

Il problema poi diventa che molto probabilmente hanno più roba di quanta ne possono tenere nell'inventario, oltre al fatto che alcuna della roba non sarà neanche su ma degli amici aggiunti alla stanza.

**Comment by MCG-server** [comment]
è vero ..fammi pensare ad una soluzione,...

**Comment by MCG-server** [comment]
ci sono più soluzioni.
la prima e che quando manca 10 minuti allo scadere della stanza al giocatore gli invia un messaggio in chat con scritto la tua stanza scadrà fra 10 minuti leva la robba dalle chest se no li perderai tutti (ma un messaggio ben visibile ..se mettii anche l opzione per modificare il messaggio e quanti gli ne invia ) cioè , mancano 10 minuti che scade la stanza di panco in chat gli invia il messaggio ma se ci sono dei giocatori che spammano lui non lo vede quindi nel opzione se metti che gli e ne invia 2 o di piu allla volta (cioè a scelta) o se no glie ne invia il messaggio a distanza di minuti (ovviamente settabili dal founder) tipo a quando mancano 10 minuti un altro quando mancano 5 ed un altro quando mancano 2 minuti (magari anche con differenze di colore che si fa man mano piu inteso e che si legge di più...ovviamente e tutto settabile dal founder).
la seconda è che si crea un chest pubblica o di più e la andranno a finere gli oggetti quando scadrà la  stanza  anche qua i messaggi con scritto fra 10 minuti tutti gli oggetti andranno nella chest pubblica perche scadrà la stanza ecc..)  che ne pensi??

**Comment by MCG-server** [comment]
ovviamente tutta la robba andrà nella chest pubblica ma non solo di quella determinata stanza ma di tutte le altre stanzi di un determinato hotel ... ovviamnete una volta finito lo spazio nella chest o nelle chet (si perche ne puoi settare piu di una cosi per avere piu spazio= apparirà un messaggio o un broadcast (meglio il broadcast) che spamma in chat per 3 volte di seguito che la/e chest pubblica/he del hotel <nomehotel>  è piena, andate a controlalre magari trovate qualcosa di utile!!! 

ovviamnete ttu quello che ho detto : messaggi,spam,intervalli tra un messaggio è l altro cioè 10 scade =messaggio , 5 minuti dallo scadere =messaggio ecc. e tutto il resto sono settabili nel config
che ne pensi?? è fattibile??

**Comment by gvlfm78** [comment]
Si potrebbero anche mettere dei messaggi di avviso al giocatore del genere, da è molto probabile che in giocatore non sia online quando tutto ciò accade.

E poi è inutile spostare tutto alla cassa pubblica, perché se imposta che la gente può aprire le casse delle stanza non affittate allora possono andare a cercare direttamente là (e magari il tizio che ha lasciato della roba nella stanza può andare a riprendersela se non è ancora passato nessuno)

**Comment by MCG-server** [comment]
be mettili i messaggi perche almeno non danno la colpa a noi founder che i loro oggetti sono rimasti dentro ...però quella cosa del commando /invetoryroom una cosa del genre la potresti mettere anche se gli amici potrebbero aver messo la loro robba ma la stanza la pagata lui quindi teoriacamente e sua ...poi se la rivuole dare indientro la da se non no
secondo me se metti il commando è meglio

**Comment by MCG-server** [comment]
io la cosa che possono entrare nelle stanza degli altri non mi piace perche di sicuro nessuno chiude la porta o altre cose

**Comment by gvlfm78** [comment]
Ci sono due diverse opzioni nel file di configurazione:

- Quando la stanza non è affittata, permetti a tutti di poter aprire porte, botole, premere leve ecc.

- Quando la stanza non è affittata, permetti a tutti di poter aprire le casse, le fornaci ecc.

Nel momento in cui la stanza viene affittata gli altri possono entrare solo se la porta è aperta, e non riusciranno a fare niente nella stanza dato che non possono premere né leve né casse.

Ritengo abbia più senso dire alla gente quando affittano una stanza che quando termina l'affitto i loro oggetti rimarranno dentro, con un'opzione nel file di configurazione per poter disabilitare il messaggio.

**Comment by MCG-server** [comment]
si è meglio cioè quando affitano la camera gli appare in chat che quando scade gli oggetti nella cassa rimaneranno dentro la cassa ??
 se si sarebbe meglio che non gli appare in chat ma sullo schermo

**Comment by gvlfm78** [comment]
Si potrebbe mettere un'opzione anche per questo.

**Comment by MCG-server** [comment]
ei ciao @gvlfm78  riguardo a quella cosa degli errori ecco il link per scaricare il mio ultimo log ..non aprirlo con notpad++ percge da tipo degli errori come in minecraft quando metti la e accentata : http://www.mediafire.com/file/63es13ela6d7m2n/latest.rar          ci sono un sacco di errori (credo ) se me li puo elencare e magari anche con le soluzioni mi faresti un grandissimo favore

**Comment by MCG-server** [comment]
@gvlfm78  asllora hai visto il mio log?

**Comment by gvlfm78** [comment]
Sì hai un infinità di problemi.

* Dovresti usare un file batch per far partire il server per usare più RAM
* Dovresti usare i plugin di EssentialsX invece di Essentials perchè quello originale non è più aggiornato
* Il plugin ServerTutorial non funziona proprio
* NoxRadarJammer non funziona proprio
* Uno degli script su Skript causa problemi

**Comment by MCG-server** [comment]
grazie @gvlfm78  in che senso un file batch ?? io uso il file .bat potresti fare un esempio di file batch ??
 ma non ho capito se essentialsx e fatto dallo stesso creatore o no cioè mi posso fidare ??
per il problema di skript sapresti dove posso reperire skript per 1.8 .....aaa non so se ti ricordi ma io ho un errore mooolto fastidioso ed è questo http://pastebin.com/JwhBbeV7

**Comment by MCG-server** [comment]
a ora ho capito nel file bat (io c'è l ho in questa estensione ) devo aumenatare la ram ok

**Comment by MCG-server** [comment]
quel errore che ho inviato prima forse ho capito era skinrestorer

**Comment by gvlfm78** [comment]
Il team originale di Essentials ha smesso di sviluppare oltre la 1.7.10, altre persone si sono messe ad aggiornarlo ed hanno creato EssentialsX, utilizzato dalla maggior parte dei server ora.

Puoi andare sul [GitHub dei creatori di Skript](https://github.com/bensku/Skript/releases) e scaricare le release da lì

**Comment by MCG-server** [comment]
grazie mi stai dando una mano enorme ...comunque riguardo a quel errorre non sono sicuro che sia skinsrestore ... fra un po provo se è skinsrestore poi ti faccio sapere @gvlfm78

**Comment by MCG-server** [comment]
ho fatto una bella cosa -... ho riniziato tutto da capo cioe ho lasciato il plugin piu difficili da settare e quelli banli lo  eleminati .. e ho laciato il mondo salvato ...(ho fatto il backup quindi se qualcosa non dovrebbe andare sono salvo) almeno cosi aggiorno tutti i plugin

**Comment by MCG-server** [comment]
@gvlfm78  allor apromesso in questo log ci sono pochi errori (vabbe i warn sono un po troppi ) questi sono gli errori che ho individuato e messo su un altro documento di testo : http://www.mediafire.com/file/ckr19ssi996qxpe/errori.rar    invece quest altro link e tutto il logs completo : http://www.mediafire.com/file/dirt47voxgq9edl/latest.rar  .. garantisco ci sono pochi errori perso non riesco a cpirli
