### ISSUE TITLE
I can't dorp items!

### ISSUE THREAD

**Issue by pocsa3** [gvlfm78/BukkitHotels#21]
I have tried to set Item_Drops to allow in the flags document in the plugin folder, but we can't drop items on the server. I have unloaded the plugin and then we could drop items. (Sorry for my english! :D)

**Comment by gvlfm78** [comment]
Have you made sure you aren't in hotels creation mode? Do /ht cm exit. Also the region flags only get updated when a room is rented / unrented when one of either allow players in free rooms or allow players to open containers in free rooms is set to true

**Comment by pocsa3** [comment]
Ahhhhhh, thank you very much! It works! :D 
Regards!
