### ISSUE TITLE
Can't Rent a Hotel?

### ISSUE THREAD

**Issue by JetSlayer** [gvlfm78/BukkitHotels#22]
First off, this plugin seems amazing. Honestly. I only have one issue. When doing the command /ht rent (HotelName) (room number) An Error message saying Invalid Hotel Room Number or Name comes in the chat? The Hotel Name on my server is StonyBrook. So there for when doing the command /ht rent StonyBrook 1 should rent  room "1" that I've set in my hotel. Its not working tho for some reason?? Advice?? I also get an error now when removing and creating a hotel in the same place!!!!! an internal error! The plugin doesn't recognize I removed the previous hotel for a new one to take its spot!

**Comment by gvlfm78** [comment]
I will look into this, but it's very likely I will not release a bugfix version of Hotels for this but instead go straight to version 1.0.0

**Comment by JetSlayer** [comment]
What can I do to fix this? Im running everything correctly

**Comment by gvlfm78** [comment]
What version of the plugin are you using? What version of bukkit/spigot?

**Comment by JetSlayer** [comment]
Im using 0.6.3 and Im ussing Paper spigot 1.9.4

**Comment by JetSlayer** [comment]
you can come join my server XeraNetwork.com and see for youself maybe Im doing something wrong?

**Comment by gvlfm78** [comment]
There was a bug in an older version of Hotels in which this would happen, if you have updated the old hotel region could have stayed so try doing _/rg list_ and looking for the _hotel-hotelName_ region and the _hotel-hotelName-roomNum_ regions (with the hotelName being the name of the old hotel that wasn't fully deleted) and then doing _/rg del hotel-hotelName_ and _/rg del hotel-hotelName-roomNum_

**Comment by gvlfm78** [comment]
@JetSlayer Is the issue still present?

**Comment by gvlfm78** [comment]
@JetSlayer Can you try with the [test version of Hotels 1.0.0](https://jenkins-gvl.rhcloud.com/job/Hotels/12/artifact/target/hotels.jar)?
