### ISSUE TITLE
domanda 

### ISSUE THREAD

**Issue by MCG-server** [gvlfm78/BukkitHotels#25]
mi sapresti dire che errore è?? http://pastebin.com/HH5MaeNz

**Comment by gvlfm78** [comment]
No, servirebbero più informazioni sul server e he plugin lo causa.

2016-08-23 1:52 GMT+01:00 MCG-server <notifications@github.com>:

**Comment by MCG-server** [comment]
potrebbe esse il mio jar (ho spigot 1.8.4) ..cioè io avevo un sito dove da li scaricavo i file jar (spigot ) mi ricordo che si chiamava "tcpa" una cosa del genere , ma è questo qua https://tcpr.ca/downloads/spigot   ?

**Comment by gvlfm78** [comment]
Sì, quelli dovrebbero funzionare, ma dovresti provare con un altra versione
dell'1.8 per vedere se è un bug in quella versione.

2016-08-23 19:40 GMT+01:00 MCG-server <notifications@github.com>:

**Comment by MCG-server** [comment]
credo che sia un plugin  perche ho un server con la stesso jar e non mi da questo erroe...tu sai a chi posso chiedere per risolvere tutti gli errori che ho nella console

**Comment by gvlfm78** [comment]
Puoi provare a inviarmi l'intero log

Il 23/ago/2016 22:23, "MCG-server" <notifications@github.com> ha scritto:

**Comment by MCG-server** [comment]
Io ti invio tutto i log (credo che ci sono tanti errori )

**Comment by gvlfm78** [comment]
Sì va bene basta che usi pastebin o qualcosa in modo che sia leggibile

**Comment by MCG-server** [comment]
Ok però non te la invio subito perché al momento non ho
Il
PC

**Comment by gvlfm78** [comment]
Fai quando puoi, tanto è a te che serve aiuto non a me.

2016-08-25 18:13 GMT+02:00 MCG-server <notifications@github.com>:
