### ISSUE TITLE
Sign text clearing

### ISSUE THREAD

**Issue by ejoyeaux** [gvlfm78/BukkitHotels#26]
I use Bukkit 1.10.2 with Hotels v0.6.4.
I can create hotel and rooms, and I verified the regions look good. (Hotel name is "mountain")
When I creat a room sign, it looks good at creation.
**However, 2 minutes after creation, all texts on the sign are reset (sign is empty).**
Another 2 minutes later, hotels deletes the sign Yaml file with the log message "[Hotels] Sign file mountain-4.yml did not match in-game hotelName and has been deleted"  ; I guess this is because the sign is empty, so the hotelname on the sign is empty too.
Any Idea what is going on ? and how to avoid the sign being emptied ?

PermissionsEx v1.23.4
Craftconomy3 v3.3-e72ac42-trv178
WorldEdit v6.1.3;7a097ca
Modifyworld v1.19.7
Vault v1.5.6-b49
WorldGuard v6.1.2;e38d98d

**Comment by gvlfm78** [comment]
It's very strange that the _whole_ sign is blank and not just some lines. 

* Can I see an example (possibly even a screenshot) of the sign before it gets cleared?
* What is the name of the hotel region and the room region of the sign?
* Could you get the contents of the mountain-4.yml file and paste them on pastebin or something and send the link here?

I see you are one of the few that actually gave me the plugin versions immediately, allowing me to exclude old versions of dependencies being a problem. (Well done)

**Comment by ejoyeaux** [comment]
Thanks for digging in this :  I attached the snapshots.
Since my hotel has five rooms, I try to make 5 signs, but I do not come so far. Right while making the 3. sign, sing 1+2 get cleread. As a last snapshot you can see all sign emptied !
I copied all signs files before they were deleted, I attached them as well. You will also find my regions.yml ; the hotel name is "mountain" (5 rooms).
While the rooms are in the first floor, the sign are in the reception on floor zero.
In case that helps, I can restart the server with a debug version of the plugin (is there any verbose option?) or you might connnect by yourself in the server (it is accessible at mycraft.spdns.eu)
![2016-09-10_20 45 47](https://cloud.githubusercontent.com/assets/22107930/18412820/c205e3de-7798-11e6-9d28-298e89d43280.png)
![2016-09-10_20 45 56](https://cloud.githubusercontent.com/assets/22107930/18412821/c207d798-7798-11e6-8541-ddfc2f0e74fc.png)
![2016-09-10_20 46 25](https://cloud.githubusercontent.com/assets/22107930/18412825/c211e2ce-7798-11e6-9a68-03d37fb805e0.png)
![2016-09-10_20 46 52](https://cloud.githubusercontent.com/assets/22107930/18412823/c20bd7a8-7798-11e6-957c-f6dba61eb38d.png)
![2016-09-10_20 47 01](https://cloud.githubusercontent.com/assets/22107930/18412822/c209afbe-7798-11e6-8328-bdf8ce15d785.png)
![2016-09-10_20 48 28](https://cloud.githubusercontent.com/assets/22107930/18412824/c21050b2-7798-11e6-907d-f9c7c982a420.png)
![2016-09-10_20 48 44](https://cloud.githubusercontent.com/assets/22107930/18412826/c2236936-7798-11e6-9539-65827d08d19c.png)
![2016-09-10_20 48 46](https://cloud.githubusercontent.com/assets/22107930/18412827/c226ec6e-7798-11e6-8c1a-765985b0439a.png)
![2016-09-10_20 49 47](https://cloud.githubusercontent.com/assets/22107930/18412828/c2283150-7798-11e6-976f-10958aee931b.png)
[YAML files.zip](https://github.com/gvlfm78/BukkitHotels/files/465585/YAML.files.zip)

**Comment by gvlfm78** [comment]
Can you try setting up a new test hotel and trying to place the signs there? Also, if possible, could you try it in a world with a fully lowercase name? I suspect somewhere in Hotels I must have made the world name forced lowercase and so it doesn't match it when the plugin checks.

**Comment by ejoyeaux** [comment]
I first to rename my world to "together". After that, the problem remained.
After that I created a second hotel in another place with two rooms (Mall-hotel].
I also tried to set the signs at another place in the first hotel.
Unfortunately, signs were still cleared in both hotels.
![2016-09-16_22 56 39](https://cloud.githubusercontent.com/assets/22107930/18601145/804a421e-7c61-11e6-9f78-222c9b9dfc50.png)
![2016-09-16_22 57 56](https://cloud.githubusercontent.com/assets/22107930/18601146/804ca284-7c61-11e6-8b8d-944ba56fece8.png)
[regions.zip](https://github.com/gvlfm78/BukkitHotels/files/477694/regions.zip)

**Comment by ejoyeaux** [comment]
(just closed the issue by inadvertance, I wanted to close the browser)

**Comment by gvlfm78** [comment]
@ejoyeaux Could you try with the latest [test version of Hotels 1.0.0](https://jenkins-gvl.rhcloud.com/job/Hotels/12/artifact/target/hotels.jar)?

**Comment by ejoyeaux** [comment]
Thnks for the update. I just downloaded the Jar you linked above and tried again. 
it looks like it WORKS  ! I did not test all combinations, but I could create 3 signs in my "mountain" hotel which are kept as expected. So it sounds like you found the problem and could fix it.

**Comment by ejoyeaux** [comment]
.... after having a look at my logs, it looks like this new version still generates various error messges, tough, not sure if they are related to additional problems. I attached the log file generated while I was creating my three signs and the generated yml for the signs. I notice the name of the world is not right (my world is called together) and that line seems to strigger an exception on hotels.
[latest.zip](https://github.com/gvlfm78/BukkitHotels/files/560199/latest.zip)

**Comment by gvlfm78** [comment]
Ah yes I see I meant to switch over from using world names to world UUIDs but instead it's been saving the world object itself, which is why you're getting such error. I'll be fixing that soon
