### ISSUE TITLE
NoSuchMethodError with 0.6.4 and 1.0

### ISSUE THREAD

**Issue by EricG66** [gvlfm78/BukkitHotels#28]
07:57:41 CONSOLE: [INFO] User issued server command: /ht c Tour1
07:57:41 CONSOLE: [INFO] World: world regions 12 Region: hotel-tour1
07:57:42 CONSOLE: ERROR]: null
07:57:42 CONSOLE: exception executing command 'ht' in plugin Hotels v1.0.0
07:57:42 CONSOLE: Source) [?:1.8.0_121]
07:57:42 CONSOLE: Source) [?:1.8.0_121]
07:57:42 CONSOLE: Source) [?:1.8.0_121]
07:57:42 CONSOLE: java.lang.NoSuchMethodError: com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;

**Comment by gvlfm78** [comment]
Is there more to the error? 
What version of bukkit/spigot and worldguard and worldedit do you have? 

Is your flags.yml the default one? 

What build of hotels 1.0.0 are you using? 

Sorry for the many questions they are to understand where the issue is as I haven't encountered it.

**Comment by EricG66** [comment]
Flags is default.

Spigot 1.11.2 R0.1-Snapshot

Worldguard 6.2.1-Snapshot-1703-85693b9

I will send you the whole error later when home
Eric

**Comment by gvlfm78** [comment]
Could you try with the[ latest test build](https://jenkins-gvl.rhcloud.com/job/Hotels/lastSuccessfulBuild/) of Hotels, and then, if the issue is still present, paste the whole error from the new build?

**Comment by EricG66** [comment]
I tried the build 72

here the full log:

[11:41:40 INFO]: Antoineprime issued server command: /ht c Tour1
[11:41:40 INFO]: World: world regions 12 Region: hotel-tour1
[11:41:40 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command
'ht' in plugin Hotels v1.0.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at
org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at
org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServer.java:650)
~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at
net.minecraft.server.v1_11_R1.PlayerConnection.handleCommand(PlayerConnection.java:1344)
[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at
net.minecraft.server.v1_11_R1.PlayerConnection.a(PlayerConnection.java:1179)
[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at
net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at
net.minecraft.server.v1_11_R1.PacketPlayInChat.a(PacketPlayInChat.java:1)
[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at
net.minecraft.server.v1_11_R1.PlayerConnectionUtils$1.run(SourceFile:13)
[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown
Source) [?:1.8.0_121]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_121]
        at net.minecraft.server.v1_11_R1.SystemUtils.a(SourceFile:46)
[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at
net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:747)
[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at
net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:399)
[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at
net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:678)
[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at
net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:576)
[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoSuchMethodError:
com.sk89q.worldguard.protection.flags.DefaultFlag.fuzzyMatchFlag(Ljava/lang/String;)Lcom/sk89q/worldguard/protection/flags/Flag;
        at
gvlfm78.plugin.Hotels.managers.WorldGuardManager.setFlags(WorldGuardManager.java:262)
~[?:?]
        at
gvlfm78.plugin.Hotels.managers.WorldGuardManager.hotelFlags(WorldGuardManager.java:282)
~[?:?]
        at gvlfm78.plugin.Hotels.Hotel.create(Hotel.java:259) ~[?:?]
        at
gvlfm78.plugin.Hotels.HotelsCreationMode.hotelSetup(HotelsCreationMode.java:86)
~[?:?]
        at
gvlfm78.plugin.Hotels.handlers.HotelsCommandExecutor.cmdCreate(HotelsCommandExecutor.java:43)
~[?:?]
        at
gvlfm78.plugin.Hotels.handlers.HotelsCommandHandler.onCommand(HotelsCommandHandler.java:72)
~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
~[spigot.jar:git-Spigot-d4f98a3-cb61ac0]
        ... 15 more

2017-03-04 5:10 GMT-05:00 gvlfm78 <notifications@github.com>:

**Comment by gvlfm78** [comment]
I found out what the problem is. The WorldGuard API regarding flags changed with WorldGuard 6.2, and Hotels hasn't been updated for it yet. Why not? Because the Maven server Hotels builds against has not been updated with this version. I will ask them to update it.

**Comment by EricG66** [comment]
Can you tell me when it will be fixed?

Eric

**Comment by gvlfm78** [comment]
I looked again on the server and realised that they changed the name and location of the projects slightly, and that it was after all updated. I therefore updated Hotels to minimum WorldEdit 6.0 and WorldGuard 6.2 in [build #75](https://jenkins-gvl.rhcloud.com/job/Hotels/75/) upwards

**Comment by EricG66** [comment]
Ok this is working now !!!!!

Thank you sooo much !!!

**Comment by gvlfm78** [comment]
Ok in case you find any other bug please tell me, also tell what build number you're on when you find it, as I am trying to remove all bugs before releasing Hotels 1.0.0
