### ISSUE TITLE
Multiple hotel owners/helpers

### ISSUE THREAD

**Issue by P0Pss** [gvlfm78/BukkitHotels#33]
Hey,

I was just wondering/hoping you could add the ability for more than 1 player to be able to work on the hotel, so give another player the same permissions as you or to just allow them to build in the hotel.

Thanks

**Comment by gvlfm78** [comment]
Who would get the payments?

**Comment by P0Pss** [comment]
The owner/creator
Its just so that others can help build, I play with a friend so it would be good if we could both work on it, we don't really mind about who gets the money

**Comment by gvlfm78** [comment]
I have now added this along with some other features in the latest test build you can try out [here](https://jenkins-gvl.rhcloud.com/job/Hotels/125/). Please report any bugs you find in the build

**Comment by gvlfm78** [comment]
Added in 1.1.0
