### ISSUE TITLE
Quando implementerai le nuove funzioni

### ISSUE THREAD

**Issue by MineFriend** [gvlfm78/BukkitHotels#35]
ciao volevo sapere quando implementerai le nuovi funzioni , cioè vorrei sapere piu o meno la data

**Comment by gvlfm78** [comment]
Quali funzioni di specifico? 

_Sent from my WIKO FEVER using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gvlfm78** [comment]
Più specificamente quali funzioni?

**Comment by MineFriend** [comment]
quelle che hai scritto nella to do list

**Comment by gvlfm78** [comment]
Ci sono alcune in particolare che vorresti implementassi per prime?

**Comment by MineFriend** [comment]
si! grazie per avermi fatto questa domanda ! te le dico subito :
la prima è il supporto della GUI (cioè e quello che ti fa vedere le camere libere e quelle occupate , vero?)

e la seconda è quella dei villager come i receptionist  , anzi ! fai che a posto del villagere ci può stare un ncp con una skin a scelta , almeno cosi posso mettere un ncp vestito elegante

**Comment by gvlfm78** [comment]
Allora, appena avrò tempo vedrò di riscrivere parte del codice sottostante per poter poi aggiungere le nuove funzioni. Serve solo un po' di pazienza perché non ho molto tempo ultimamente.
