### ISSUE TITLE
Not casting block to sign correctly

### ISSUE THREAD

**Issue by ICEconchy** [gvlfm78/BukkitHotels#36]
Server Version: Spigot 1.11.1-R0.1-SNAPSHOT
Hotel version: 1.1.2
Error: https://pastebin.com/5ctV9b0e

Happens when creating a room renting sign

**Comment by gvlfm78** [comment]
Please try the [latest test version](https://jenkins-gvl.rhcloud.com/job/Hotels/131/) available here and report whether the error still occurs.
