### ISSUE TITLE
"An internal error has occurred..."

### ISSUE THREAD

**Issue by MartianMH** [gvlfm78/BukkitHotels#37]
Version of Bukkit/Spigot: (This is what it says on server startup) "This server is running CraftBukkit version git-Bukkit-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)"

Hotels version: v1.1.2

config.yml: https://pastebin.com/waHd35GT

Full console error, from server startup: https://pastebin.com/urrMNZJx

Whenever I type any command having to do with this plugin, whether it's "/ht help" "/ht commands" or "/ht sethome" for example, it always displays this same message: "An internal error occurred while attempting to perform this command."

**Comment by gvlfm78** [comment]
What version of WorldEdit do you have?

**Comment by MartianMH** [comment]
I have Worldedit version v5.6.3 .

**Comment by gvlfm78** [comment]
Please update to [WorldEdit 6.1.7.3](https://dev.bukkit.org/projects/worldedit/files/2460562) and the check if the error is still present.

**Comment by MartianMH** [comment]
Haha, that seems to fix the issue! Thanks so much for your help.
