### ISSUE TITLE
NPE when renting but owner is offline

### ISSUE THREAD

**Issue by promorrom** [gvlfm78/BukkitHotels#38]
If the owner of the hotel is offline and an user right clicks the sign, the money gets deducted but the sign does'nt updates.

I get this error in the console:

[Server] ERROR Could not pass event PlayerInteractEvent to Hotels v1.1.2 15.09 22:18:55 [Server] INFO org.bukkit.event.EventException 15.09 22:18:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:228) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerInteractManager.interact(PlayerInteractManager.java:463) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:759) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:52) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInBlockPlace.a(PacketPlayInBlockPlace.java:1) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131] 15.09 22:18:55 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131] 15.09 22:18:55 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131] 15.09 22:18:55 [Server] INFO Caused by: java.lang.NullPointerException 15.09 22:18:55 [Server] INFO at net.milkbowl.vault.economy.AbstractEconomy.depositPlayer(AbstractEconomy.java:50) ~[?:?] 15.09 22:18:55 [Server] INFO at gvlfm78.plugin.Hotels.managers.HTSignManager.payOwners(HTSignManager.java:355) ~[?:?] 15.09 22:18:55 [Server] INFO at gvlfm78.plugin.Hotels.managers.HTSignManager.rentRoom(HTSignManager.java:300) ~[?:?] 15.09 22:18:55 [Server] INFO at gvlfm78.plugin.Hotels.managers.HTSignManager.useRoomSign(HTSignManager.java:265) ~[?:?] 15.09 22:18:55 [Server] INFO at gvlfm78.plugin.Hotels.HTListener.onSignUse(HTListener.java:62) ~[?:?] 15.09 22:18:55 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131] 15.09 22:18:55 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_131] 15.09 22:18:55 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_131] 15.09 22:18:55 [Server] INFO at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_131] 15.09 22:18:55 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[minecraft_server.jar:git-Spigot-db6de12-18fbb24] 15.09 22:18:55 [Server] INFO ... 17 more

**Comment by gvlfm78** [comment]
Thank you for reporting this bug correctly. It should now be fixed in the latest test version of Hotels you can find [here.](https://jenkins-gvl.rhcloud.com/job/Hotels/133/)
