### ISSUE TITLE
Can't create signs, "Sign file does not exist!"

### ISSUE THREAD

**Issue by MSMatrixGamer** [gvlfm78/BukkitHotels#4]
![captura](https://cloud.githubusercontent.com/assets/11777342/6973633/5504e524-d98c-11e4-9c77-10b13224d5b2.PNG)

So that, When I create the signs, all is right. There are the files, the hotels all. But it says that there aren't the files.

**Comment by gvlfm78** [comment]
It could have to do with you running it as a remote server and it not being
able to access files properly. See if you can run the server as admin
Il 02/apr/2015 23:04 "MSMatrixGamer" <notifications@github.com> ha scritto:

**Comment by MSMatrixGamer** [comment]
So, I have to close Filezilla or what. I tried it but still not working.

**Comment by Blackyvk** [comment]
I'm having the same issue, I'm on linux all the groups and users are fine... i dont know whats wrong.

**Comment by gvlfm78** [comment]
Are you using the recommended versions for the plugins? I would need to
replicate the bug to be able to fix it.  Are you able to create the sign
and then it doesn't work or immediately as you place the sign and exit the
edit screen does the error come up?
Il 07/apr/2015 02:06 "Blackyvk" <notifications@github.com> ha scritto:
>
> I'm having the same issue, I'm on linux all the groups and users are
fine... i dont know whats wrong.

**Comment by MSMatrixGamer** [comment]
The problem happens when I right clic the sign

**Comment by Blackyvk** [comment]
i'm using spigot 1.8 and hotels 0.3.2 and yes, happens when I right clic the sign after it's created, the sign stays even after restart.

**Comment by MSMatrixGamer** [comment]
Yeah Im using spigot 1.8 too.

**Comment by gvlfm78** [comment]
Do you all get the same error all the time for every sign?

Have you tried stopping and starting again the server?

**Comment by MSMatrixGamer** [comment]
Yes I've tried.

**Comment by Blackyvk** [comment]
I even tried to upgrade spigot to 1.8.3 and it didnt work, any ideas? hotels room signs creation work, just the sign doesnt let us rent a room because "the sign file doesnt exist" maybe its some kind case sensitive compatibility and thats why the plugin cant find the file? linux is very annoying with it.

**Comment by MSMatrixGamer** [comment]
Pls we need answer.p

**Comment by gvlfm78** [comment]
I have not been able to replicate your bugs. What version of the plugin are you using?

**Comment by Blackyvk** [comment]
Like I said 0.3.2 on 1.8 and also 1.8.3  on Linux SO
do we need specific versions of other plugins or ???

**Comment by gvlfm78** [comment]
Try with the recommended versions of the plugins. If it doesn't work with those do tell me.

Also, do you get any error in the console?

**Comment by gvlfm78** [comment]
This doesn't happen to me in my new release so I am going to release it soon hoping it fixes your problems.

**Comment by MSMatrixGamer** [comment]
Thanks, when are you going to release it?

**Comment by gvlfm78** [comment]
I released the new version a week ago. Is the bug still present?

**Comment by gvlfm78** [comment]
Hotels 0.4 is now out. IS the bug you people are having still present? If yes, try updating your plugins such as WorldEdit, WorldGuard, Vault and Essentials (maybe PermissionsEx?) through the new links I put on the project page - http://dev.bukkit.org/bukkit-plugins/hotels/ (Under the Recommended section)

**Comment by CherryDestiny** [comment]
Hi, I downloaded the plugin 10 minutes ago and I came across this issue aswell, I've the latest of all recommended plugins you've listed and it still gives me the error after restarting multiple times, if you can provide any help please do, also if it makes things easier, join my server and have a look for yourself. juddus.com:25567

**Comment by gvlfm78** [comment]
What plugins do you have installed (/plugins). Also, what happens when you do /hotels? and, do you get any error in the console? Did you check in /plugins/Hotels/Signs folder so see if the sign files are actually there?

**Comment by CherryDestiny** [comment]
http://gyazo.com/a595d00b7a0a4d51a097d01fa00a90ed  <- plugins and no, no errors are in the console. and yes the sign files do exist in the folder

**Comment by gvlfm78** [comment]
Have you tried copying that server setup but just keeping Hotels, WorldGuard, WorldEdit, Essentials and Vault? To see if the problem has to do with plugins conflicting.

**Comment by CherryDestiny** [comment]
No, I tried it on my personal pc, exactly the same setup as on my host, and
it works fine, what does this mean?

**Comment by CherryDestiny** [comment]
No, I tried it on my personal pc, exactly the same setup as on my host, and it works fine, what does this mean?

**Comment by gvlfm78** [comment]
It might have to do with running the server as administrator or something similar, we need to do some testing on that

**Comment by CherryDestiny** [comment]
It shouldn't need administrative powers to read a file that itself created?

**Comment by gvlfm78** [comment]
I don't know, it might, because if you think of it if you put a copy of a sign file from another server in the Signs folder and then start the server it will read it as its own file, even if it didn't put it there. I need confirmation that administrator power is what is causing this bug to see about fixing it.

**Comment by Lyndeno** [comment]
Maybe for now you can add a command to rent a room.

Also maybe it would be a better idea to just put the sign information in the config file where it can be read.

**Comment by gvlfm78** [comment]
What do you mean?  The sign information is already in the config, the sign
is just for display. A command would require access to the config to rent
the room.
Il 25/lug/2015 02:00, "Lyndeno" <notifications@github.com> ha scritto:

**Comment by Lyndeno** [comment]
I mean instead of having the sign information in it's own separate files maybe have the signs saved in the main plugin config file.

**Comment by gvlfm78** [comment]
Just a question. Does the locale.yml file work?

**Comment by Lyndeno** [comment]
How do I figure out if it's working?

**Comment by gvlfm78** [comment]
If the messages that are in it work, such as doing /hotels list

**Comment by Lyndeno** [comment]
The messages do work. I also noticed my hotel doesn't show up in the list even though it exists.

**Comment by gvlfm78** [comment]
Yes that would be because anything using the HotelsFileFinder class doesn't work, not that the custom yml files don't work. That means the problem is within that class and how it looks for the files and that's where the bug is.

**Comment by gvlfm78** [comment]
Today I decided to boot my system into Linux instead of Windows and continue developing Hotels. And what did I find out? That I had the same problem as you people! And so I went and looked into the code and found the part that listed files was only compatible with Windows, and went ahead and changed it and it now works on my system. So I released Hotels 0.4.1 with the fix to this bug.

**Comment by Lyndeno** [comment]
Thank you

**Comment by gvlfm78** [comment]
Does it work for you too?

**Comment by Lyndeno** [comment]
I'm going to reboot my server and we'll see.

**Comment by Lyndeno** [comment]
I'm still getting the error.

**Comment by gvlfm78** [comment]
When doing what exactly? And did you use the new version of the plugin? Did you try removing the previous file and sign and trying again?

**Comment by Lyndeno** [comment]
I created a new hotel and sign and it still does not work. I'm using hosthorde if that helps.

**Comment by gvlfm78** [comment]
Does /ht list work?

**Comment by Lyndeno** [comment]
/ht list shows the start and end of the list, but my hotels are not in it

**Comment by gvlfm78** [comment]
WorldGuard.

**Comment by Lyndeno** [comment]
what about it?

**Comment by gvlfm78** [comment]
The /ht list works on WorldGuard regions and doesn't even use files. There's something going on with your WorldGuard

**Comment by Lyndeno** [comment]
I'm using worldguard 6.1, is that incompatible?

**Comment by gvlfm78** [comment]
That should be the compatible version together with WorldEdit 6.1, downloaded from their project pages http://dev.bukkit.org/bukkit-plugins/worldedit/files/61-world-edit-6-1-up-to-mc-1-8-7/
 and http://dev.bukkit.org/bukkit-plugins/worldguard/files/46-world-guard-6-1/

**Comment by gvlfm78** [comment]
Doing /rg list shows some hotel-hotelname and hotel-hotelname-roomnum regions?

**Comment by Lyndeno** [comment]
Yeah that works

**Comment by gvlfm78** [comment]
How about /ht rlist? And are the hotel names in caps by any chance?

**Comment by gvlfm78** [comment]
What are exact names of your hotels?

**Comment by Lyndeno** [comment]
I think I figured it out
Lyndeno-Grand

dashes don't seem to work correctly

**Comment by Lyndeno** [comment]
Never mind it's still not working after I removed the dashes

**Comment by gvlfm78** [comment]
That would make sense, since this is how the Hotel name is checked:
if(id.startsWith("hotel-")){ //If it's a hotel
				if(!id.matches("^hotel-.+-.+")){ //if it's not a room
And it would match the second one since it has a second dash in the name

**Comment by Lyndeno** [comment]
Is there a limit to amount of letters in the hotel name?

**Comment by gvlfm78** [comment]
Well, it should fit in one line on the sign

**Comment by Lyndeno** [comment]
This is weird. I made a hotel called test with 1 room, signs work fine.

I make my hotel LyndenoGrand, signs don't work.

**Comment by Lyndeno** [comment]
Sign:
  time: 2880
  hotel: lyndenogrand
  room: 1
  cost: 250.0
  region: hotel-lyndenogrand-1
  location:
    world: spawn
    coords:
      x: 548
      y: 5
      z: -666

Is there anything in here that is wrong? This is the sign file that "doesn't" exist

**Comment by gvlfm78** [comment]
Did you delete the old lyndeno-grand hotel?

**Comment by Lyndeno** [comment]
Yes

**Comment by Lyndeno** [comment]
I think using capital letters in the name is screwing it up. I created lyndenogrand and it works.

**Comment by gvlfm78** [comment]
This is what it does when you right click:
File signFile = HConH.getFile("Signs"+File.separator+hotelName.toLowerCase()+"-"+roomNum+".yml");
				if(signFile.exists()){
And unless the actual sign file got created containing a capital letter, it should work.

**Comment by Lyndeno** [comment]
I guess that is the issue, the filename has a capital letter in it.

**Comment by gvlfm78** [comment]
Ok then that is probably the issue. I don't know when I'll have time to fix that, now I need to go.

**Comment by Lyndeno** [comment]
Well it works for now, so no rush.

**Comment by Lyndeno** [comment]
Thanks for the help!
