### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by promorrom** [gvlfm78/BukkitHotels#41]
Hi, when I set in config to use the Spanish translation, the plugin stops to show texts at commands.

I look that in enGB, the locale version is 4, but in Spanish is 1.

I translated a few more things for spanish, right now the 271 terms are translated.

I hope the fix, or I will have to translate the entire locale.yml

Thank you, and nice plugin!

**Comment by gvlfm78** [comment]
What do you mean by "the plugin stops to show texts at commands"? Do you have any screenshots?
