### ISSUE TITLE
Some problems here! :/ 

### ISSUE THREAD

**Issue by Szhweetie** [gvlfm78/BukkitHotels#42]
Hi dude. Really love ur plugin, looks beutiful and awesome and this would suit me so well on the server. But i have some problems. 

My server is 1.8 still just cuz I like the old way of Minecraft:). I downloaded the 1.8 version from the versions tab on the bukkit site and installed it. I have Vault, WorldGuard, WorldEdit and EConomy also. 
I watched this totorial and did exactly what this dude did and the problem is that when I set the signs on the hotel rooms the sign doesn't "get colors" and you cant click it, but in chat, it says 2 times in a row that it was successfully placed/made. I don't know if this has with the decision, some plugin more missing, coding error, bug, or something else. But I have tried also with a completely fresh server to just install these plugins and none else to see if some other plugins were causing Hotels to not work correctly but still the same problem, I checked the console but there is nothing, nothing wrong, no errors or other hints that could help to solve it. Now im contacting you to see if you could help me with this so i could have a great time with this awesome plugin you made. 

All thanks, best regards Szhweetie

**Comment by gvlfm78** [comment]
Why are you still on 1.8 and what do you mean by "1.8 version front the versions tab"?

**Comment by Szhweetie** [comment]
On the bukkit site, https://dev.bukkit.org/projects/hotels
Because I don't really like the new Minecraft sort of, but the version should not be a difference right? 
I downloaded your 1.8 verision on your files tab here https://dev.bukkit.org/projects/hotels/files?filter-game-version=2020709689%3A531

**Comment by gvlfm78** [comment]
There's no such thing as a 1.8 version, all Hotels versions should work on 1.8, you should be using the latest. Also I don't like the new Minecraft either, that's why I created my other plugin OldCombatMechanics.

**Comment by Szhweetie** [comment]
Yeah, iknow new Minecraft is kinda bad, but I have used the new version also and it didn't work, do you know in some way how I can solve it? Would appreciate much if helped me out mate 👍 <3

**Comment by gvlfm78** [comment]
First of all install the newest version of Hotels. Then check if there are any errors in the console or such things and if it doesn't work.

Also tell me what version of Worldedit and Worldguard you are using

**Comment by Szhweetie** [comment]
Im gonna download the latest verision of the hotel in a sec, 
On WorldEdit and WorldGuard it says:
WorldGuard-6.2.1
WorldEdit-6.1.7.3

**Comment by gvlfm78** [comment]
You should be using Worldguard 6.2 and Worldedit 6.1.7.3

**Comment by Szhweetie** [comment]
http://prntscr.com/h4elwp
http://prntscr.com/h4em2x
http://prntscr.com/h4em8m

Pictures of the problem!

**Comment by gvlfm78** [comment]
1. Make sure you are using Worldguard 6.2 as it is the last version that supports 1.8

2. Have you tried using the /room command instead of placing the sign manually?

**Comment by Szhweetie** [comment]
I am using Worldguard 6.2. 

Nope havnt tried that! Didnt evern know you could do that, but how do people rent rooms then?

**Comment by gvlfm78** [comment]
Renting rooms is the same, the command just unites creating a room and making the sign into one command, you need to be looking at an empty sign when you run it

**Comment by Szhweetie** [comment]
Eeey, now it works, thanks for helmping me out and for the quick answers, the /room command worked! 

All cred to you <3

**Comment by Szhweetie** [comment]
One more question, Im using GroupCommands and i have set a own Admin rank. Can i add a permission so i can destroy blocks in the hotel rooms because im admin, it says "Sorry you cant break that block here".

**Comment by gvlfm78** [comment]
That would need to be the Worldguard bypass permission. You can find the exact permission you need in the Worldguard documentation

**Comment by Szhweetie** [comment]
Thanks man, fixed that too :)

**Comment by Szhweetie** [comment]
Have a great day
