### ISSUE TITLE
Jenkins not work

### ISSUE THREAD

**Issue by Lunatik934** [gvlfm78/BukkitHotels#43]
https://jenkinsci-gvl-jenkins.1d35.starter-us-east-1.openshiftapps.com/job/Hotels/ not work :x

**Comment by gvlfm78** [comment]
I have moved it to https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com
but have not had the time to make it work properly again

**Comment by gvlfm78** [comment]
Ok it is now back up again at https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/Hotels/
