### ISSUE TITLE
Price multipliers not being detected

### ISSUE THREAD

**Issue by Suhi123** [gvlfm78/BukkitHotels#45]
http://prntscr.com/hkyw6n What is this ?

**Comment by gvlfm78** [comment]
It appears to be an error with the price detection.
Does it work if you use any other price multiplier or write the price out fully?

**Comment by Suhi123** [comment]
Nope its not working at all

**Comment by gvlfm78** [comment]
Which price multipliers have you tried?

Does writing out the price fully without any multipliers work?

**Comment by luc819** [comment]
same thnig here

**Comment by luc819** [comment]
[hotels]
{hotelname}
is working but i am not able to creat a sign to rent

**Comment by gvlfm78** [comment]
Does the multiplier work if you use the _/room_ command instead of making the sign manually?

**Comment by luc819** [comment]
yes

**Comment by gvlfm78** [comment]
Ok it looks like the manual creation of signs is completely broken.

**Comment by gvlfm78** [comment]
Alright @Suhi123 @luc819 I'm not sure if it's fully fixed but I have managed to fix the manual palcing of signs. Please try [this test build ](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/Hotels/7/)and tell me if it is working.
