### ISSUE TITLE
Missing permissions or different from webpage

### ISSUE THREAD

**Issue by CreativeLand** [gvlfm78/BukkitHotels#46]
Good evening,
I'm the owner of a small server and I implemented Hotels as a feature for my players.
However, I can't make it available because some of the permissions I found on this page [https://github.com/gvlfm78/BukkitHotels/wiki/Permissions](url) are missing or don't work.

My server is running CraftBukkit version git-Spigot-596221b-9a1fc1e (MC: 1.12) (Implementing API version 1.12-R0.1-SNAPSHOT)

this is the config.yml of the plugin: [https://pastebin.com/iWQBDBUR](url)

Best regards,
CL

**Comment by gvlfm78** [comment]
Do you know exactly which ones do not work?

**Comment by CreativeLand** [comment]
At the moment I only found out that hotels.creationmode, hotels.delete.user and hotels.delete.rooms.user are not working.
If you need more informations I can contact the player who notified me and ask for a list of permission.
Since hotels is a plugin available only to vip users, I temporarily fixed the situation by giving them the hotels.* permission (which works perfectly).

**Comment by gvlfm78** [comment]
Hmm that's strange because in issue #44 I determined that the permission is indeed **hotels.creationmode**. What version of Hotels are you running?

**Comment by CreativeLand** [comment]
At the moment I'm running Hotels 1.1.4

**Comment by gvlfm78** [comment]
What are you using to assign players the permissions?

Are there any permissions you gave the players that _do_ work?

**Comment by CreativeLand** [comment]
I use PermissionsEx 1.23.4, at the moment different permissions work, such as hotels.creationmode and others, like hotels.create.user. we couldn't try everything because we weren't able to complete the creation of an hotel.

**Comment by gvlfm78** [comment]
Does giving the player **hotels.*** give them access to all commands and features?

**Comment by CreativeLand** [comment]
Yes, it does. at the moment I'm using that permission to let my players use Hotels

**Comment by gvlfm78** [comment]
Can you check if this issue is still present in the [latest test build](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/Hotels/lastSuccessfulBuild/)?

**Comment by gvlfm78** [comment]
@CreativeLand are you still alive?

**Comment by CreativeLand** [comment]
Hi @gvlfm78 ,
at the moment we are rebuilding the whole server. We will insert the latest test build you provided me and I'll let you know if the issue is still present.
Regards

**Comment by gvlfm78** [comment]
Alright let me know if it works.

**Comment by FrukTik** [comment]
The command does not work
/ ht delete
/ ht delr
But Permissions to players are given out.
