### ISSUE TITLE
Room Sign doesn't work

### ISSUE THREAD

**Issue by CCCCarsten** [gvlfm78/BukkitHotels#47]
Hi!
Spigot 1.12.2, Hotels v1.1.4 (trying newest devbuild, too). No errors at logfile.
Reception signs are working, but not the room signs:
Manually added. Automatic I have not understood :)

![hotel1](https://user-images.githubusercontent.com/18105655/35476263-25d25194-03ad-11e8-9c67-cc1e4c636aab.jpg)

CCCCarsten

**Comment by gvlfm78** [comment]
So did you make the sign by writing it out yourself?

**Comment by CCCCarsten** [comment]
Yes. In the format you can see on the picture above. Automatic sign I have tried but I have not understood what format I have to use in the command (signs are always empty after trying, but room was been set).

**Comment by gvlfm78** [comment]
You can use `/room <hotelName> <time> <price> <roomNum>`. So, in this case, it would be `/room Schneekanone 1d 50 2`

**Comment by CCCCarsten** [comment]
Okay, gvlfm78.... this functions. Hmpf.... don't know why the automatic functions now. But I enjoy now... thank you very much.

**Comment by gvlfm78** [comment]
When I get time I will actually fix the manual creation of room signs...
