### ISSUE TITLE
Sign does nothing when owner offline

### ISSUE THREAD

**Issue by kianlechner** [gvlfm78/BukkitHotels#48]
Hi, 

When the hotel owner is offline and I click on the sign, nothing happens. No money is deducted or anything. Its like i never right clicked.

**Comment by gvlfm78** [comment]
Hotels & server version?

**Comment by gvlfm78** [comment]
This might have been related to manual sign placement not working at all, can you please try the [latest test version](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/Hotels/7/) and tell me if the issue is still there?
