### ISSUE TITLE
Spigot update checker broken

### ISSUE THREAD

**Issue by doitliketyler** [gvlfm78/BukkitHotels#49]
Hello. I'm getting this console error when a player joins the server. Thoughts?

https://pastebin.com/raw/AxincvGc

**Comment by gvlfm78** [comment]
It looks like this has something to do with the update checker. I'll be having a look at this some time soon.

**Comment by EricG66** [comment]
You can check this post about the updater:

https://www.spigotmc.org/threads/update-checking.264850/

**Comment by gvlfm78** [comment]
@EricG66 interesting, however at this point it might be worth changing the way the update checker works entirely.

**Comment by gvlfm78** [comment]
Ok I have changed the Spigot Update Checker entirely to use the SpigetAPI instead. However, I have not been able to test it working so if someone here @Fargus5 @EricG66 @doitliketyler can try the [latest test build](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/Hotels/lastSuccessfulBuild/) and see if the error still appears it would be very helpful.

**Comment by EricG66** [comment]
I will test it today

**Comment by gvlfm78** [comment]
Ok this should be fixed now in latest test build @EricG66 @Fargus5 @doitliketyler . Although you won't get any messages regarding updates because it is already the newest version.
