### ISSUE TITLE
Economy Enhanced 

### ISSUE THREAD

**Issue by KhaarNaj** [gvlfm78/BukkitHotels#50]
Why not adding a new feature:  "sized cuboid" (so 3 variables that can be configured in the config file (or put "any" to let it free like now), for length, depth and width) that players need to buy to enhance hotel size (and so on there could be a cuboids number at start => also configured in the config file). Then the price to create an hotel.

All of this to make it more dynamic with currency system. The cuboid then could be created external sides with glass that give nothing when you break them (or any configured block if you want to put that option to chose in the config file), so you can see in game what you're paying for. Then they select a cuboid in game with worldedit tool and they write a command (or any GUI menu) to place (upper, down, right,left,front,behind) using MC 3axial system.

Check Towny way of working, it's somekind of similar to what I'm talking to you.

Maybe this can help you to better understand the cuboid part: https://youtu.be/9TeVfb-iMkw?t=2m14s

**Comment by gvlfm78** [comment]
I'm still not entirely sure what this means and how it would fit with this plugin but bug fixing still takes priority over new features. However, I do have plans on rewriting this plugin from scratch in a few months, when I will have plenty more time, and I might get this in there when I do.

**Comment by gvlfm78** [comment]
Project has been moved to [GitLab](https://gitlab.com/gvlfm78/hotels).
