### ISSUE TITLE
Cannot sethome for rooms

### ISSUE THREAD

**Issue by eykkey** [gvlfm78/BukkitHotels#51]
First of all nice plugin. Everything seems to work fine.
When i do /ht sethome, it always sets home for the hotels itself not the room.
Example when i go in the region of room 1 and do cmd /ht sethome. It keeps setting the home for the hotel itself and not the room.
Please help.

**Comment by gvlfm78** [comment]
Are you the owner of the hotel?  
Are you the renter of the room?

**Comment by eykkey** [comment]
Im the owner of the hotel.
Tried to rent the room(which worked fine) and set the spawn for the room itself, but it just kept setting the spawn for the hotel itself and not the indivudial room.
also owner of the server.

**Comment by gvlfm78** [comment]
So you are _in_ the room that you rented while also being the owner of the hotel and do _/ht sethome_ and it sets the hotel home?

**Comment by eykkey** [comment]
Yes exactly

**Comment by eykkey** [comment]
Also Tried to sethome for the rooms that no one was owner of

**Comment by gvlfm78** [comment]
Well if you are not the renter of the room you will not be able to set the room home.
