### ISSUE TITLE
Hotel Creation does not work

### ISSUE THREAD

**Issue by hernikplays** [gvlfm78/BukkitHotels#52]
When I select with the WE wand and type /ht c name ot says internal server error. The server runs 1.12.2 Spigot. Also /ht list does not work

**Comment by gvlfm78** [comment]
Can you please try with the [latest test build](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/Hotels/lastSuccessfulBuild/) and see if the problem is still there?

**Comment by NiKunHax** [comment]
I am bugged too.

**Comment by gvlfm78** [comment]
@hernikplays what is the error in the console?
