### ISSUE TITLE
Problema con la creazione dell'hotel/stanze e lista hotel.

### ISSUE THREAD

**Issue by ghost** [gvlfm78/BukkitHotels#53]
Ciao, ho provato a creare l'hotel ma mi da un errore, stessa cosa se faccio /ht list o provo a creare una stanza, ho provato a scaricare la beta come hai detto all'altro americano ma il sito web non va.

https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/Hotels/

**Comment by gvlfm78** [comment]
Riprova ora, ho fatto ripartire il server

**Comment by NiKunHax** [comment]
Scaricata ma mi da comunque errore:

Tipo errore nel creare region WorldGuard NoClassDefFound, e altre cose del plugin hotels

**Comment by gvlfm78** [comment]
Puoi copiare l'errore ed inviarlo qui? Altrimenti non ho modo di aggiustarlo...

Dovrei anche sapere che versione di bukkit stai usando

**Comment by NiKunHax** [comment]
Spigot 1.8.8

SpigotLib - ERROR REPORT - NoClassDefFoundError
com/sk89q/worldguard/protection/flags/registry/FlagRegistry
 #1: LINE 64 in FILE Hotel.java (gvlfm78.plugin.Hotels.Hotel.exists)
 #2: LINE 50 in FILE HTCreationMode.java (gvlfm78.plugin.Hotels.HTCreationMode.hotelSetup)
 #3: LINE 37 in FILE HTCmdSurrogate.java (gvlfm78.plugin.Hotels.handlers.HTCmdSurrogate.cmdCreate)
 #4: LINE 22 in FILE HTCmdExecutor.java (gvlfm78.plugin.Hotels.handlers.HTCmdExecutor.lambda$new$1)
 #5: LINE 106 in FILE HTSubCommand.java (gvlfm78.plugin.Hotels.utilities.HTSubCommand.run)
 #6: LINE 112 in FILE HTCmdExecutor.java (gvlfm78.plugin.Hotels.handlers.HTCmdExecutor.onCommand)
 #7: LINE 44 in FILE PluginCommand.java (org.bukkit.command.PluginCommand.execute)
 #8: LINE 141 in FILE SimpleCommandMap.java (org.bukkit.command.SimpleCommandMap.dispatch)
 #9: LINE 83 in FILE CustomCommandMap.java (gyurix.commands.CustomCommandMap.dispatch)

**Comment by NiKunHax** [comment]
Ho un pl che mi fa vedere gli errori dal game (SpigotLib)

**Comment by gvlfm78** [comment]
Questo errore di solito significa che devi aggiornare WorldGuard

**Comment by NiKunHax** [comment]
Ma se aggiorno wg non so perche' non vanno piu le region e non posso manco crearne di nuove

non hai una versione piu vecchia wg 6.1?

**Comment by NiKunHax** [comment]
Per il resto ho WorldEdit 6.1, Vault e Java 8 perfetti.

**Comment by NiKunHax** [comment]
E poi c'è scritto che worldguard 6.2 va solo su MC 1.9+

**Comment by gvlfm78** [comment]
Sul download di WorldGuard c'è scritto che la 6.2 dovrebbe supportare 1.7-1.12
