### ISSUE TITLE
Rent a room in the console

### ISSUE THREAD

**Issue by Momonche** [gvlfm78/BukkitHotels#54]
Hello,
Can you create a command to rent a room through the console, like:
/ht rent (hotelname) (room) (player) (time ?)

Thank for your responding in the discussion section on spigot :)

**Comment by Momonche** [comment]
Some news about that ?

**Comment by gvlfm78** [comment]
Sorry I have been busy rewriting my other plugin InactiveLockette. What kind of use do you have in mind for this command?

**Comment by Momonche** [comment]
I want to rent a room through my website's store, so I need to send the command in the console to rent a room to the player.
But actually it's not possible to execute a command in the console to rent a room to a player for a specified time.

**Comment by gvlfm78** [comment]
Ah, I see.

**Comment by Momonche** [comment]
Some news ?

**Comment by Blamo27** [comment]
@gvlfm78 ?

**Comment by gvlfm78** [comment]
I'll have this be in the rewrite. I'll be starting the rewrite properly in the next few weeks, hopefully I'll actually get it done this time...

**Comment by gvlfm78** [comment]
Project has been moved to [GitLab](https://gitlab.com/gvlfm78/hotels).
