### ISSUE TITLE
Commands permissions not working correctly

### ISSUE THREAD

**Issue by FrukTik** [gvlfm78/BukkitHotels#57]
Do not work commands 
/ ht delete 
/ ht delr 
/ht sethome
/ht home

Permissions Iroquam issued, but the team does not work. The server does not budge. In the * mode, the teams work, but I can not issue * to all players. I use PermissionsEx 1.23.5 Paper 1327  Hotels 1.1.5

**Comment by gvlfm78** [comment]
What do you mean by "the teams"?

**Comment by FrukTik** [comment]
The player enters the chat:
/ ht delete
/ ht delr
/ ht sethome
/ ht home
and nothing happens.

**Comment by gvlfm78** [comment]
Does the _/hotels_ command work?

**Comment by FrukTik** [comment]
https://youtu.be/cKYUzJepp2g

**Comment by gvlfm78** [comment]
So it _does_ show a message... It says you don't have permission to execute the command.  
Therefore, that means this is a permissions issue. I will try to have a look at this tomorrow.

**Comment by gvlfm78** [comment]
Can you please create a new issue for the things you mentioned in your last comment? This is to reduce the confusion and allow me to work on the issues separately.
