### ISSUE TITLE
Any user can break room signs regardless of permissions

### ISSUE THREAD

**Issue by vD3STINY** [gvlfm78/BukkitHotels#60]
Dude, there is something wrong with your plugin. If someone will destroy sign at cuboid. it just says: "Sign doesn't exit". The thing is that sign file is deleting from main folder of plugin. Pls fix this

**Comment by gvlfm78** [comment]
Is this the same issue as #59 ?

**Comment by vD3STINY** [comment]
Same message, but I exactly mean situation when you destroy sign by default group inside cuboid. A sign disappears only for 1 sec, it is logic cuz I have cuboid but after this it is saying "Sign doesnt exit" :/

**Comment by gvlfm78** [comment]
Sorry but I don't think I understand the situation you are describing

**Comment by vD3STINY** [comment]
If you destroy sign at area which you can't edit (place or destroy block), just at cuboid, without permission to destroy sign, YOU CAN DESTROY SIGN! After this file with sign is missing

**Comment by gvlfm78** [comment]
Oh ok now I see... Yes, that will need to be fixed...

**Comment by vD3STINY** [comment]
thx :)

**Comment by vD3STINY** [comment]
When will it be fixed?

**Comment by gvlfm78** [comment]
When I'll have time

**Comment by gvlfm78** [comment]
Ok @vD3STINY I think I found where the problem was. Please try [this test build](https://jenkinsgvl-jenkins-gvl.1d35.starter-us-east-1.openshiftapps.com/job/Hotels/lastSuccessfulBuild/) and tell me if it is still an issue.

**Comment by vD3STINY** [comment]
Can't download this build, I got an error like this: https://imgur.com/a/pShnNfN

**Comment by gvlfm78** [comment]
Please try the link again now, the server should be back up

**Comment by vD3STINY** [comment]
Yes, It worked but there is another bug
