### ISSUE TITLE
Set up the economics of the plugin

### ISSUE THREAD

**Issue by FrukTik** [gvlfm78/BukkitHotels#61]
The plangin has a mistake in the economy, when the hotel has 2 owners, they are both credited with money for the rooms. In 2 hours you can undermine the economy of the server.

**Comment by gvlfm78** [comment]
Wait, what do you mean the hotel has two owners?

**Comment by FrukTik** [comment]
Usually, with the help of the team adds to the owners of the private and makes a huge profit.

**Comment by gvlfm78** [comment]
There's meant to be one owner and multiple helpers, how are you adding more owners?

**Comment by FrukTik** [comment]
Using the WorldGuard command / rg addowner <name of hotel region>

2018-06-24 22:37 GMT+03:00 gvlfm78 <notifications@github.com>:

**Comment by gvlfm78** [comment]
Well, you're not meant to do that. You're meant to use the hotels commands and add helpers, which get build permissions but none of the money.
