### ISSUE TITLE
Room flags

### ISSUE THREAD

**Issue by vD3STINY** [gvlfm78/BukkitHotels#62]
I would like to change flag of region in config for MEMBERS, only FOR MEMBERS, but there isn't any option to change set this flag... I would like change INTERACT : deny to INTERACT: -g members allow to give members of room access to doors, but it didn't work. So I tried to manually change flag of region (room region ofc.) 
But when room is expires. my manually added flag it's just gone! For etc. I will kick someone from a room ( etc. /ht Player123 hotel 1 ), Region changes to flag interact NON_MEMBERS: DENY. But there isn't any way to change in config called flags.yml to set correct flag to correct GROUP.

**Comment by gvlfm78** [comment]
What exactly did you change in the flags.yml?

**Comment by vD3STINY** [comment]
INTERACT: -g members allow

**Comment by gvlfm78** [comment]
What did you set `allowPlayersToOpenContainersInFreeRooms` as?

**Comment by vD3STINY** [comment]
I tried FALSE and TRUE, it doesn't help. Your plugin has problem when hotel is in other cuboid, like town. You should add in your plugin option that when play rent region, it adds flag: INTERACT MEMBERS ALLOW

**Comment by gvlfm78** [comment]
Did you check the region priorities?

**Comment by vD3STINY** [comment]
What do you mean? I just see that rooms don't have INTERACT for MEMBERS set to ALLOW, that's it. It is required to have access to doors by players

**Comment by gvlfm78** [comment]
Once you set that in the flags.yml, you need to rent the room at least once for the flags to update
