### ISSUE TITLE
Update to 1.13?

### ISSUE THREAD

**Issue by Ocelots101** [gvlfm78/BukkitHotels#63]
Can you update this to 1.13 please because I am trying to downgrade my server for this plugin but it wont let me unless I start a new world witch I wont want to do. Please update!

**Comment by gvlfm78** [comment]
Sorry I have been inactive lately because I am planning a full rewrite of this plugin. What exactly prevents it from working with 1.13?

**Comment by Ocelots101** [comment]
Thank you for replying fast! When I put it in the plugins folder, it does not even show up in the server with 1.13. I try the cmd and nothing recognizes the plugin. I hope you can get this fixed or done pretty soon and I can’t wait for the rewrite of the plugin! Thank you! :)

**Comment by gvlfm78** [comment]
Do the server loading messages contain anything pertaining Hotels?

Also, I would try re-downloading the jar just in case the file is corrupt and thus not showing up.

**Comment by Ocelots101** [comment]
I don't think the server loading messages say anything about Hotels. I also have tried that. I will paste what my loading msg said in console below.

04.09 15:50:43 [Server] INFO *** WARNING: This is a development build. It is not meant for production server usage! Please keep backups and update frequently.
04.09 15:50:43 [Server] INFO Loading libraries, please wait...
04.09 15:50:48 [Server] INFO Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
04.09 15:50:48 [Server] INFO Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
04.09 15:50:48 [Server] INFO Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
04.09 15:50:48 [Server] INFO Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
04.09 15:50:48 [Server] INFO Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
04.09 15:50:48 [Server] INFO Loaded 0 recipes
04.09 15:50:48 [Server] WARN Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498]
04.09 15:50:48 [Server] WARN Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
04.09 15:50:48 [Server] WARN Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
04.09 15:50:48 [Server] WARN Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
04.09 15:50:48 [Server] WARN Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
04.09 15:50:48 [Server] INFO Loaded 0 recipes
04.09 15:50:48 [Server] INFO Starting minecraft server version 1.13
04.09 15:50:48 [Server] INFO Loading properties
04.09 15:50:48 [Server] INFO Default game type: SURVIVAL
04.09 15:50:49 [Server] INFO This server is running CraftBukkit version git-Spigot-1503de9-200b239 (MC: 1.13) (Implementing API version 1.13-R0.1-SNAPSHOT)
04.09 15:50:49 [Server] INFO Using 4 threads for Netty based IO
04.09 15:50:49 [Server] INFO Server Ping Player Sample Count: 12
04.09 15:50:49 [Server] INFO Debug logging is disabled
04.09 15:50:49 [Server] INFO Generating keypair
04.09 15:50:49 [Server] INFO Starting Minecraft server on 45.35.63.82:25580
04.09 15:50:49 [Server] INFO Using epoll channel type
04.09 15:50:53 [Server] INFO Set PluginClassLoader as parallel capable
04.09 15:50:53 [Server] ERROR Could not load 'plugins/AreaShop.jar' in folder 'plugins'
04.09 15:50:53 [Server] INFO org.bukkit.plugin.UnknownDependencyException: WorldGuard
04.09 15:50:53 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:50:53 [Server] INFO at org.bukkit.craftbukkit.v1_13_R1.CraftServer.loadPlugins(CraftServer.java:314) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:50:53 [Server] INFO at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:213) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:50:53 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:50:53 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
04.09 15:50:53 [Server] INFO Loading WorldEdit v7.0.0-SNAPSHOT;3809-38cff7c
04.09 15:50:53 [Server] INFO Loading GetID v1.3
04.09 15:50:53 [Server] INFO Loading Essentials vTeamCity
04.09 15:50:53 [Server] INFO Loading EssentialsGeoIP vTeamCity
04.09 15:50:53 [Server] INFO Loading EssentialsChat vTeamCity
04.09 15:50:53 [Server] INFO Loading PermissionsEx v1.23.4
04.09 15:50:53 [Server] INFO Loading ViaVersion v1.5.0
04.09 15:50:53 [Server] INFO ViaVersion 1.5.0 is now loaded, injecting!
04.09 15:50:53 [Server] INFO Loading block mapping...
04.09 15:50:53 [Server] INFO Loading item mapping...
04.09 15:50:53 [Server] INFO Loading new tags...
04.09 15:50:53 [Server] INFO Loading enchantments...
04.09 15:50:53 [Server] INFO Loading sound mapping...
04.09 15:50:54 [Server] INFO Loading BuycraftX v10.1.3
04.09 15:50:54 [Server] INFO Loading Vault v1.5.6-b49
04.09 15:50:54 [Server] INFO Loading GriefPrevention v16.8
04.09 15:50:54 [Server] INFO Loading EssentialsSpawn vTeamCity
04.09 15:50:54 [Server] INFO Loading ChestShop v3.9.2 (build 86)
04.09 15:50:54 [Server] INFO Loading LockettePro v2.9.0
04.09 15:50:54 [Server] INFO Loading EssentialsProtect vTeamCity
04.09 15:50:54 [Server] INFO Loading ScoreboardStats v0.10.6
04.09 15:50:54 [Server] INFO Loading Trading v3.2
04.09 15:50:54 [Multicraft] Skipped 10 lines due to rate limit (30/s)
04.09 15:50:54 [Server] INFO Loaded 524 recipes
04.09 15:50:55 [Server] INFO -------- World Settings For [world] --------
04.09 15:50:55 [Server] INFO Mob Spawn Range: 4
04.09 15:50:55 [Server] INFO Cactus Growth Modifier: 100%
04.09 15:50:55 [Server] INFO Cane Growth Modifier: 100%
04.09 15:50:55 [Server] INFO Melon Growth Modifier: 100%
04.09 15:50:55 [Server] INFO Mushroom Growth Modifier: 100%
04.09 15:50:55 [Server] INFO Pumpkin Growth Modifier: 100%
04.09 15:50:55 [Server] INFO Sapling Growth Modifier: 100%
04.09 15:50:55 [Server] INFO Wheat Growth Modifier: 100%
04.09 15:50:55 [Server] INFO NetherWart Growth Modifier: 100%
04.09 15:50:55 [Server] INFO Vine Growth Modifier: 100%
04.09 15:50:55 [Server] INFO Cocoa Growth Modifier: 100%
04.09 15:50:55 [Server] INFO Entity Activation Range: An 32 / Mo 32 / Mi 16 / Tiv true
04.09 15:50:55 [Server] INFO Entity Tracking Range: Pl 48 / An 48 / Mo 48 / Mi 32 / Other 64
04.09 15:50:55 [Server] INFO Hopper Transfer: 8 Hopper Check: 1 Hopper Amount: 1
04.09 15:50:55 [Server] INFO Random Lighting Updates: false
04.09 15:50:55 [Server] INFO Custom Map Seeds:  Village: 10387312 Desert: 14357617 Igloo: 14357618 Jungle: 14357619 Swamp: 14357620 Monument: 10387313Ocean: 14357621 Shipwreck: 165745295 Slime: 987234911
04.09 15:50:55 [Server] INFO Max TNT Explosions: 100
04.09 15:50:55 [Server] INFO Tile Max Tick Time: 50ms Entity max Tick Time: 50ms
04.09 15:50:55 [Server] INFO Item Merge Radius: 2.5
04.09 15:50:55 [Server] INFO Allow Zombie Pigmen to spawn from portal blocks: true
04.09 15:50:55 [Server] INFO Item Despawn Rate: 6000
04.09 15:50:55 [Server] INFO Arrow Despawn Rate: 1200
04.09 15:50:55 [Server] INFO View Distance: 10
04.09 15:50:55 [Server] INFO Experience Merge Radius: 3.0
04.09 15:50:55 [Server] INFO Zombie Aggressive Towards Villager: true
04.09 15:50:55 [Server] INFO Nerfing mobs spawned from spawners: false
04.09 15:50:55 [Server] INFO -------- World Settings For [world_nether] --------
04.09 15:50:55 [Server] INFO Mob Spawn Range: 4
04.09 15:50:55 [Multicraft] Skipped 59 lines due to rate limit (30/s)
04.09 15:50:55 [Server] INFO Preparing spawn area: 28%
04.09 15:50:55 [Server] INFO Preparing spawn area: 32%
04.09 15:50:55 [Server] INFO Preparing spawn area: 36%
04.09 15:50:55 [Server] INFO Preparing spawn area: 40%
04.09 15:50:55 [Server] INFO Preparing spawn area: 44%
04.09 15:50:55 [Server] INFO Preparing spawn area: 48%
04.09 15:50:56 [Server] INFO Preparing spawn area: 52%
04.09 15:50:56 [Server] INFO Preparing spawn area: 56%
04.09 15:50:56 [Server] INFO Preparing spawn area: 60%
04.09 15:50:56 [Server] INFO Preparing spawn area: 64%
04.09 15:50:56 [Server] INFO Preparing spawn area: 68%
04.09 15:50:56 [Server] INFO Preparing spawn area: 72%
04.09 15:50:56 [Server] INFO Preparing spawn area: 76%
04.09 15:50:56 [Server] INFO Preparing spawn area: 80%
04.09 15:50:56 [Server] INFO Preparing spawn area: 84%
04.09 15:50:56 [Server] INFO Preparing spawn area: 88%
04.09 15:50:56 [Server] INFO Preparing spawn area: 92%
04.09 15:50:56 [Server] INFO Preparing spawn area: 96%
04.09 15:50:56 [Server] INFO Preparing spawn area: 100%
04.09 15:50:56 [Server] INFO Preparing start region for level 1 (Seed: 7224531791465172630)
04.09 15:50:56 [Server] INFO Preparing spawn area: 4%
04.09 15:50:56 [Server] INFO Preparing spawn area: 8%
04.09 15:50:56 [Server] INFO Preparing spawn area: 12%
04.09 15:50:56 [Server] INFO Preparing spawn area: 16%
04.09 15:50:56 [Server] INFO Preparing spawn area: 20%
04.09 15:50:56 [Server] INFO Preparing spawn area: 24%
04.09 15:50:56 [Server] INFO Preparing spawn area: 28%
04.09 15:50:56 [Server] INFO Preparing spawn area: 32%
04.09 15:50:56 [Server] INFO Preparing spawn area: 36%
04.09 15:50:56 [Server] INFO Preparing spawn area: 40%
04.09 15:50:56 [Server] INFO Preparing spawn area: 44%
04.09 15:50:56 [Server] INFO Preparing spawn area: 48%
04.09 15:50:57 [Server] INFO Preparing spawn area: 52%
04.09 15:50:57 [Server] INFO Preparing spawn area: 56%
04.09 15:50:57 [Server] INFO Preparing spawn area: 60%
04.09 15:50:57 [Server] INFO Preparing spawn area: 64%
04.09 15:50:57 [Server] INFO Preparing spawn area: 68%
04.09 15:50:57 [Server] INFO Preparing spawn area: 72%
04.09 15:50:57 [Server] INFO Preparing spawn area: 76%
04.09 15:50:57 [Server] INFO Preparing spawn area: 80%
04.09 15:50:57 [Server] INFO Preparing spawn area: 84%
04.09 15:50:57 [Server] INFO Preparing spawn area: 88%
04.09 15:50:57 [Server] INFO Preparing spawn area: 92%
04.09 15:50:57 [Server] INFO Preparing spawn area: 96%
04.09 15:50:57 [Server] INFO Preparing spawn area: 100%
04.09 15:50:57 [Server] INFO Preparing start region for level 2 (Seed: 7224531791465172630)
04.09 15:50:57 [Server] INFO Preparing spawn area: 4%
04.09 15:50:57 [Server] INFO Preparing spawn area: 8%
04.09 15:50:57 [Server] INFO Preparing spawn area: 12%
04.09 15:50:57 [Server] INFO Preparing spawn area: 16%
04.09 15:50:57 [Server] INFO Preparing spawn area: 20%
04.09 15:50:57 [Server] INFO Preparing spawn area: 24%
04.09 15:50:57 [Server] INFO Preparing spawn area: 28%
04.09 15:50:57 [Server] INFO Preparing spawn area: 32%
04.09 15:50:57 [Multicraft] Skipped 11 lines due to rate limit (30/s)
04.09 15:50:57 [Server] INFO Preparing spawn area: 80%
04.09 15:50:57 [Server] INFO Preparing spawn area: 84%
04.09 15:50:57 [Server] INFO Preparing spawn area: 88%
04.09 15:50:57 [Server] INFO Preparing spawn area: 92%
04.09 15:50:57 [Server] INFO Preparing spawn area: 96%
04.09 15:50:57 [Server] INFO Preparing spawn area: 100%
04.09 15:50:57 [Server] INFO Enabling WorldEdit v7.0.0-SNAPSHOT;3809-38cff7c
04.09 15:50:58 [Server] INFO Using com.sk89q.worldedit.bukkit.adapter.impl.Spigot_v1_13_R1 as the Bukkit adapter
04.09 15:50:59 [Server] WARN Unknown block: minecraft:tnt[unstable=false]
04.09 15:50:59 [Server] WARN Unknown block: minecraft:tnt[unstable=true]
04.09 15:50:59 [Server] INFO WEPIF: Using the Bukkit Permissions API.
04.09 15:50:59 [Server] INFO Enabling GetID v1.3
04.09 15:50:59 [Server] INFO Version 1.3 has been enabled!
04.09 15:50:59 [Server] INFO Created by SpiFioY!
04.09 15:50:59 [Server] INFO Enabling Essentials vTeamCity
04.09 15:50:59 [Server] INFO Bukkit version format changed. Version not checked.
04.09 15:50:59 [Server] INFO git-Spigot-1503de9-200b239 (MC: 1.13)
04.09 15:50:59 [Server] INFO 1.13-R0.1-SNAPSHOT
04.09 15:50:59 [Server] INFO Using locale en_US
04.09 15:50:59 [Server] INFO Using locale en_US
04.09 15:50:59 [Server] INFO [Vault][Economy] Essentials Economy hooked.
04.09 15:50:59 [Server] INFO Essentials: Using config file enhanced permissions.
04.09 15:50:59 [Server] INFO Permissions listed in as player-commands will be given to all users.
04.09 15:50:59 [Server] INFO Enabling EssentialsGeoIP vTeamCity
04.09 15:50:59 [Server] INFO This product includes GeoLite data created by MaxMind, available from http://www.maxmind.com/.
04.09 15:50:59 [Server] INFO Enabling EssentialsChat vTeamCity
04.09 15:50:59 [Server] INFO Enabling PermissionsEx v1.23.4
04.09 15:50:59 [Server] INFO Initializing file backend
04.09 15:50:59 [Server] INFO Permissions file successfully reloaded
04.09 15:50:59 [Server] INFO WEPIF: PermissionsEx detected! Using PermissionsEx for permissions.
04.09 15:50:59 [Server] INFO [Vault][Permission] PermissionsEx hooked.
04.09 15:50:59 [Server] INFO [Vault][Chat] PermissionsEx_Chat hooked.
04.09 15:50:59 [Server] INFO Essentials: Using PermissionsEx based permissions.
04.09 15:50:59 [Server] INFO Enabling ViaVersion v1.5.0
04.09 15:50:59 [Server] INFO Enabling BuycraftX v10.1.3
04.09 15:50:59 [Server] INFO Validating your server key...
04.09 15:51:00 [Server] INFO Fetching all server packages...
04.09 15:51:00 [Server] WARN A connection to https://plugin.buycraft.net/ was leaked. Did you forget to close a response body?
04.09 15:51:00 [Server] INFO Enabling GriefPrevention v16.8
04.09 15:51:00 [Server] INFO Finished loading configuration.
04.09 15:51:00 [Server] INFO 19 total claims loaded.
04.09 15:51:01 [Server] INFO Customizable messages loaded.
04.09 15:51:01 [Server] INFO Finished loading data (File Mode).
04.09 15:51:01 [Server] INFO GriefPrevention requires Vault for economy integration.
04.09 15:51:01 [Server] INFO Attempting to load Vault...
04.09 15:51:01 [Server] INFO Vault loaded successfully!
04.09 15:51:01 [Server] INFO Looking for a Vault-compatible economy plugin...
04.09 15:51:01 [Server] INFO Hooked into economy: Essentials Economy.
04.09 15:51:01 [Server] INFO Ready to buy/sell claim blocks!
04.09 15:51:01 [Server] INFO Boot finished.
04.09 15:51:01 [Server] INFO Enabling EssentialsSpawn vTeamCity
04.09 15:51:01 [Server] INFO Enabling ChestShop v3.9.2 (build 86)
04.09 15:51:01 [Server] INFO Vault loaded! Found an economy plugin!
04.09 15:51:01 [Server] INFO Enabling LockettePro v2.9.0
04.09 15:51:02 [Server] INFO Enabling EssentialsProtect vTeamCity
04.09 15:51:02 [Server] INFO Enabling ScoreboardStats v0.10.6
04.09 15:51:02 [Server] INFO Registered replacers: [PlayerPingVariable, BungeeCordVariables, BukkitGlobalVariables, GeneralVariables, BukkitVariables, VaultVariables, GriefPreventionVariables]
04.09 15:51:02 [Server] INFO Enabling Trading v3.2
04.09 15:51:02 [Server] INFO Trading has been enabled
04.09 15:51:02 [Server] INFO Vault and Economy have been found!
04.09 15:51:02 [Server] INFO Enabling Banknotes v1.8.0
04.09 15:51:02 [Server] INFO Server permissions file permissions.yml is empty, ignoring it
04.09 15:51:02 [Server] INFO Time elapsed: 7190 ms
04.09 15:51:02 [Server] Startup Done (8.287s)! For help, type "help"
04.09 15:51:02 [Server] INFO ViaVersion detected server version: 1.13(393)
04.09 15:51:02 [Server] INFO Found economy provider Vault
04.09 15:51:02 [Server] INFO Checking for Updates ... 
04.09 15:51:02 [Server] WARN Plugin Essentials vTeamCity generated an exception while executing task 25
04.09 15:51:02 [Server] INFO org.yaml.snakeyaml.constructor.ConstructorException: Can't construct a java object for tag:yaml.org,2002:com.earth2me.essentials.settings.Spawns; exception=java.lang.NoSuchFieldException: typeDefinitions
04.09 15:51:02 [Server] INFO in 'reader', line 1, column 1:
04.09 15:51:02 [Server] INFO spawns: 
04.09 15:51:02 [Server] INFO ^
04.09 15:51:02 [Server] INFO at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:314) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:51:02 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:204) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:51:02 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:193) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:51:02 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:159) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:51:02 [Server] INFO at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:146) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:51:02 [Server] INFO at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:51:02 [Server] INFO at org.yaml.snakeyaml.Yaml.load(Yaml.java:467) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:51:02 [Server] INFO at com.earth2me.essentials.storage.YamlStorageReader.load(YamlStorageReader.java:47) ~[?:?]
04.09 15:51:02 [Server] INFO at com.earth2me.essentials.storage.AbstractDelayedYamlFileReader.run(AbstractDelayedYamlFileReader.java:37) ~[?:?]
04.09 15:51:02 [Server] INFO at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:51:02 [Server] INFO at org.bukkit.craftbukkit.v1_13_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:51:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_181]
04.09 15:51:02 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_181]
04.09 15:51:02 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
04.09 15:51:02 [Server] INFO Caused by: org.yaml.snakeyaml.error.YAMLException: java.lang.NoSuchFieldException: typeDefinitions
04.09 15:51:02 [Server] INFO at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.constructJavaBean2ndStep(BukkitConstructor.java:294) ~[?:?]
04.09 15:51:02 [Server] INFO at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:149) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:51:02 [Server] INFO at com.earth2me.essentials.storage.BukkitConstructor$ConstructBukkitMapping.construct(BukkitConstructor.java:275) ~[?:?]
04.09 15:51:02 [Server] INFO at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:309) ~[spigot-1.13.jar:git-Spigot-1503de9-200b239]
04.09 15:51:05 [Multicraft] Skipped 10 lines due to rate limit (30/s)
04.09 15:51:05 [Server] INFO Fetched due players (0 found).
04.09 15:51:40 [Server] INFO CONSOLE issued server command: /list

**Comment by Ocelots101** [comment]
I got Hotel plugin working but now I am receiving a problem with A, world guard not working and B, it giving me errors when creating hotel name and rooms for no reason??

**Comment by gvlfm78** [comment]
Well, there's no way for Hotels to work without WorldGuard, so we're going to have to wait until that updates...

**Comment by Ocelots101** [comment]
Alright, thank you so much for helping.

**Comment by RetroMC** [comment]
Hello, if it should fail at a current worldguard/worldedit, there is already a version 7.0.0 for 1.13.1 Here is the link
http://www.enginehub.org/

**Comment by AwesomeKalin** [comment]
WorldGuard for 1.13 has now been released.

**Comment by gvlfm78** [comment]
Ok. In  ~ two weeks I will have plenty of time to work on this. Please remind me around then.

**Comment by xPazz** [comment]
nice

**Comment by igtimemiller** [comment]
Did you update the plugin? Thank you very much for the support

**Comment by gvlfm78** [comment]
I will be starting this very soon, as I now have both the time and my computer setup to do so.

**Comment by gvlfm78** [comment]
Project has been moved to [GitLab](https://gitlab.com/gvlfm78/hotels).
