### ISSUE TITLE
Worldguard/Worldedit 7.0.0 for 1.13.X

### ISSUE THREAD

**Issue by RetroMC** [gvlfm78/BukkitHotels#64]
Hello, if the update should fail at a current worldguard/worldedit, there is already a version 7.0.0 for 1.13.X Here is the link
http://www.enginehub.org/

I hope it helps to update hotels because I love the plugin

**Comment by gvlfm78** [comment]
Alright. Just keep reminding me every now and then and eventually I'll get to rewriting the plugin.

**Comment by PowerMiner69** [comment]
Hello, i am very interested in updating the plugin for version 1.13.2. How about that?

**Comment by gvlfm78** [comment]
@PowerMiner69 I am going to be starting coding the new Hotels over on [GitLab ](https://gitlab.com/gvlfm78/hotels) soon, after I fix some major issues with my other plugin OldCombatMechanics.

**Comment by gvlfm78** [comment]
Project has been moved to [GitLab](https://gitlab.com/gvlfm78/hotels).
