### ISSUE TITLE
I can't enter in the room when I buy it

### ISSUE THREAD

**Issue by HeyImKata** [gvlfm78/BukkitHotels#67]
I probably did something wrong but I can't find out my mistake.
I made an hotel with 9 rooms.
I placed a wooden door and I want it to be impossible to enter in the room unless you buy it. 
So I set : allowPlayersIntoFreeRooms: false 

On my server, when I de-op myself, I can open all the doors and when I buy a room I can't reach the room. I want the opposite ^^
Thanks for your answers !

**Comment by gvlfm78** [comment]
Project has been moved to [GitLab](https://gitlab.com/gvlfm78/hotels).
