### ISSUE TITLE
Are this plugin working for bukkit server 1.7.10?

### ISSUE THREAD

**Issue by Hyasintus** [gvlfm78/BukkitHotels#7]
If yes
why i get this error
http://youtu.be/f5q8_yGc3Xc

**Comment by gvlfm78** [comment]
Do you get any error in the console?

**Comment by Hyasintus** [comment]
No

**Comment by gvlfm78** [comment]
It could be a problem caused by version incompatibility. Hotels is compiled with Bukkit 1.8 and not 1.7 and might therefore not work with 1.7.10. Although I have some reports of people that have actually used it and it worked, so then it might be a problem with the versions of Vault, WorldEdit and WorldGuard.

**Comment by Hyasintus** [comment]
Ok

2015-07-10 0:48 GMT+07:00 gvlfm78 <notifications@github.com>:

**Comment by gvlfm78** [comment]
Have you tried updating the WorldEdit, WorldGuard and Vault versions to the latest?

**Comment by Hyasintus** [comment]
yes

**Comment by gvlfm78** [comment]
So all of the recommended versions from this https://www.spigotmc.org/resources/hotels.2047/ page?

**Comment by Hyasintus** [comment]
i don't understand what are you say

(i'm Indonesian)

**Comment by gvlfm78** [comment]
Try installing these plugin versions:
http://dev.bukkit.org/media/files/865/213/Vault.jar
http://builds.enginehub.org/job/worldedit/7094/download/worldedit-bukkit-6.1.1-SNAPSHOT-dist.jar
https://hub.spigotmc.org/jenkins/job/Spigot-Essentials/lastSuccessfulBuild/artifact/Essentials/target/Essentials-2.x-SNAPSHOT.jar
http://www.curse.com/bukkit-plugins/minecraft/permissionsex#

For this one you need to take the .jar file out of the .zip
http://builds.enginehub.org/job/worldguard/7151/download/worldguard-6.1.1-SNAPSHOT.zip

**Comment by Hyasintus** [comment]
still not work :(

**Comment by gvlfm78** [comment]
What version of 1.7.10 are you using?

**Comment by Hyasintus** [comment]
what are you mean?

**Comment by gvlfm78** [comment]
Do */version* on your server - you should get something like this:
[Image](http://i.imgur.com/3DjHdYP.png)

**Comment by Hyasintus** [comment]
This server is running CraftBukkit version git-Bukkit-1.7.9-R0.2-24-g07d4558-b3116jnks (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPS
HOT)

**Comment by gvlfm78** [comment]
You should be using all of the latest compatible 1.7.10 versions of the various plugins you have installed.
So:
Vault: http://dev.bukkit.org/media/files/792/396/Vault-1.4.1.jar
WorldEdit: http://dev.bukkit.org/media/files/880/435/worldedit-bukkit-6.1.jar
WorldGuard: http://dev.bukkit.org/media/files/881/691/worldguard-6.1.jar
Essentials: http://ci.ess3.net/repository/download/bt9/6255:id/Essentials.zip%21/Essentials.jar
PermissionsEx: http://dev.bukkit.org/media/files/882/988/PermissionsEx-1.22.9.jar

**Comment by Hyasintus** [comment]
i'm give up to try your plugin, dude
Bye :) !

**Comment by gvlfm78** [comment]
Sorry for not having been able to fix your issue. You should update to 1.8 anyway, it's been out for quite a while now.
