### ISSUE TITLE
Type commands, but nothing happening

### ISSUE THREAD

**Issue by DrStill** [gvlfm78/BukkitHotels#8]
Hello

When I type the command for creating hotels, I have nothing, no return in chat. I've try the last and the previous version of the plugin but no change. 

I'm on spigot 1.8.3.

Thanks

**Comment by DrStill** [comment]
sorry for this useless post. 

I have update worldedit, world guard and vault. and now the plug in looks works.

Thanks

**Comment by gvlfm78** [comment]
Good to know you found a solution. Other users have had the same problem with this and other versions of Bukkit and I believe they still haven't found a solution.
