### ISSUE TITLE
Reception Signs stop working

### ISSUE THREAD

**Issue by Lyndeno** [gvlfm78/BukkitHotels#9]
@gvlfm78 When I create a reception sign all is well, but after a while this happens and I have to recreate the sign.
![2015-07-26_00001](https://cloud.githubusercontent.com/assets/13490857/8895278/fdae6be2-3390-11e5-8678-0d7743470fdc.jpg)

**Comment by gvlfm78** [comment]
The reception sign errors should be fixed in Hotels 0.4.2. Do tell me if that is not the case.
